/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.AnalyticsReportAck;
import org.openapitools.client.model.ErrorMessage;
import org.openapitools.client.model.ForesightAnalyticsReportConstraints;
import org.openapitools.client.model.SecurityFreezeErrorMessage;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AnalyticsApi
 */
@Disabled
public class AnalyticsApiTest {

    private final AnalyticsApi api = new AnalyticsApi();

    /**
     * Generate foresight analytics non-CRA report for the customer - Personal
     *
     * Generate a foresight analytics non-CRA report for a given customer. The report includes benchmarking and forecasting data for a customer based on inputs of account and transaction data as permitted by the customer, and segments (e.g., postal code) provided by the partner. A consumer is not required to generate this report.  If no account type of checking, credit card, or savings is found, the service will return an HTTP 400 Bad Request.  This is a premium service, billable per every successful API call for non-testing customers. A successful call to this API will generate a foresight analytics report which can be retrieved via Get Report by Customer.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateForesightAnalyticsNonCraReportTest() throws ApiException {
        String customerId = null;
        String userType = null;
        ForesightAnalyticsReportConstraints foresightAnalyticsReportConstraints = null;
        String callbackUrl = null;
        AnalyticsReportAck response = api.generateForesightAnalyticsNonCraReport(customerId, userType, foresightAnalyticsReportConstraints, callbackUrl);
        // TODO: test validations
    }

}
