/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.CustomerAuthorizationDetails;
import org.openapitools.client.model.ErrorMessage;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CustomerAuthorizationDetailsApi
 */
@Disabled
public class CustomerAuthorizationDetailsApiTest {

    private final CustomerAuthorizationDetailsApi api = new CustomerAuthorizationDetailsApi();

    /**
     * Returns customer authorization details for the institution login identification.
     *
     * The endpoint provides customer authorization details like authorization start date, authorization end date against the requested institution login id  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCustomerAuthorizationDetailsTest() throws ApiException {
        Long institutionLoginId = null;
        CustomerAuthorizationDetails response = api.getCustomerAuthorizationDetails(institutionLoginId);
        // TODO: test validations
    }

}
