/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.BrandingWrapper;
import org.openapitools.client.model.CertifiedInstitutions;
import org.openapitools.client.model.ErrorMessage;
import org.openapitools.client.model.GetInstitutionsByRoutingNumber200Response;
import org.openapitools.client.model.InstitutionWrapper;
import org.openapitools.client.model.Institutions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InstitutionsApi
 */
@Disabled
public class InstitutionsApiTest {

    private final InstitutionsApi api = new InstitutionsApi();

    /**
     * Get Certified Institutions
     *
     * Search for financial institutions by certified product.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCertifiedInstitutionsTest() throws ApiException {
        String search = null;
        Integer start = null;
        Integer limit = null;
        String type = null;
        List<String> supportedCountries = null;
        CertifiedInstitutions response = api.getCertifiedInstitutions(search, start, limit, type, supportedCountries);
        // TODO: test validations
    }

    /**
     * Get Certified Institutions With RSSD
     *
     * Search for certified financial institutions w/RSSD.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCertifiedInstitutionsWithRSSDTest() throws ApiException {
        String search = null;
        Integer start = null;
        Integer limit = null;
        String type = null;
        List<String> supportedCountries = null;
        CertifiedInstitutions response = api.getCertifiedInstitutionsWithRSSD(search, start, limit, type, supportedCountries);
        // TODO: test validations
    }

    /**
     * Get Institution by ID
     *
     * Get financial institution details by ID.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getInstitutionTest() throws ApiException {
        Long institutionId = null;
        InstitutionWrapper response = api.getInstitution(institutionId);
        // TODO: test validations
    }

    /**
     * Get Institution Branding by ID
     *
     * Return the branding information for a financial institution.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getInstitutionBrandingTest() throws ApiException {
        Long institutionId = null;
        BrandingWrapper response = api.getInstitutionBranding(institutionId);
        // TODO: test validations
    }

    /**
     * Get Institutions
     *
     * Search for financial institutions.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getInstitutionsTest() throws ApiException {
        String search = null;
        Integer start = null;
        Integer limit = null;
        String type = null;
        List<String> supportedCountries = null;
        Institutions response = api.getInstitutions(search, start, limit, type, supportedCountries);
        // TODO: test validations
    }

    /**
     * Get Institutions by Routing Number
     *
     * Get institution details for a given routing number. The endpoint will return an error if it is unable to find a match for the routing number or if the routing number provided is not the correct length.  &lt;br&gt;&lt;br&gt; Please note, this endpoint only returns FIs that are mapped to Mastercard financial institutions.  Not every institution can be mapped as not every institution type has a routing number.   _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getInstitutionsByRoutingNumberTest() throws ApiException {
        Integer routingNumber = null;
        GetInstitutionsByRoutingNumber200Response response = api.getInstitutionsByRoutingNumber(routingNumber);
        // TODO: test validations
    }

}
