/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ErrorMessage;
import org.openapitools.client.model.PaymentEnablementBundle;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PaymentEnablementBundleApi
 */
@Disabled
public class PaymentEnablementBundleApiTest {

    private final PaymentEnablementBundleApi api = new PaymentEnablementBundleApi();

    /**
     * Fetch all the requested details using the account ID
     *
     * This bundled API will return any or all of the Payments endpoints in one API call using account ID. This includes, Account Simple details, ACH details, Account Owner, and Account Balance. This requires initial setup to determine which endpoints are included in the API response. For Account Balance, You can define an additional query parameter &#x60;balance_cache_interval&#x60; to specify the time interval of the last cached balance.  This parameter will be used by the server to determine whether the cached balance is still valid or if it needs to be refreshed.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAccountDetailsByAccountIdTest() throws ApiException {
        String customerId = null;
        String accountId = null;
        String include = null;
        Integer balanceCacheInterval = null;
        PaymentEnablementBundle response = api.getAccountDetailsByAccountId(customerId, accountId, include, balanceCacheInterval);
        // TODO: test validations
    }

    /**
     * Fetch all the requested field details using institution login ID
     *
     * This bundled API returns any or all of the Payments endpoints in one API call using institution login ID. This includes, Account Simple details, ACH details, Account Owner, and Account Balance. This requires initial setup to determine which endpoints are included in the API response. For Account Balance, You can define an additional query parameter &#x60;balance_cache_interval&#x60; to specify the time interval of the last cached balance.  This parameter is used by the server to determine whether the cached balance is still valid or if it needs to be refreshed.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAccountDetailsByInstitutionLoginIdTest() throws ApiException {
        String customerId = null;
        Long institutionLoginId = null;
        String include = null;
        Integer balanceCacheInterval = null;
        PaymentEnablementBundle response = api.getAccountDetailsByInstitutionLoginId(customerId, institutionLoginId, include, balanceCacheInterval);
        // TODO: test validations
    }

}
