/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import java.math.BigDecimal;
import org.openapitools.client.model.ErrorMessage;
import org.openapitools.client.model.FcraPaymentSuccessIndicators;
import java.time.LocalDate;
import org.openapitools.client.model.PaymentSuccessIndicator;
import org.openapitools.client.model.PaymentSuccessIndicators;
import org.openapitools.client.model.PaymentSuccessIndicatorsProperties;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PaymentSuccessIndicatorApi
 */
@Disabled
public class PaymentSuccessIndicatorApiTest {

    private final PaymentSuccessIndicatorApi api = new PaymentSuccessIndicatorApi();

    /**
     * Generate FCRA Payment Success Indicators
     *
     * Payment Success Indicator (PSI) allows the user to evaluate the likelihood of a specific ACH transaction resulting in either an insufficient funds return (NSF) or an unauthorized return due to first- or third-party fraud. PSI is powered by a machine learning model trained on consumer-permissioned data. PSI provides a risk assessment, which includes a real-time balance check, predictive risk scores forecasting a consumer’s likelihood of having sufficient funds over a 10-day period, a real-time score predicting the likelihood of an unauthorized return, and risk attributes to explain and enhance decisioning. Provision and use of this report is subject to all applicable obligations of the FCRA and any applicable analogous state law. This product may only be used for the stated permissible purpose under the FCRA. _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateFcraPaymentSuccessIndicatorsTest() throws ApiException {
        String customerId = null;
        String accountId = null;
        PaymentSuccessIndicatorsProperties paymentSuccessIndicatorsProperties = null;
        String purpose = null;
        PaymentSuccessIndicators response = api.generateFcraPaymentSuccessIndicators(customerId, accountId, paymentSuccessIndicatorsProperties, purpose);
        // TODO: test validations
    }

    /**
     * Generate Non-FCRA Payment Success Indicators
     *
     * Payment Success Indicator (PSI) allows the user to evaluate the likelihood of a specific ACH transaction resulting in either an insufficient funds return (NSF) or an unauthorized return due to first- or third-party fraud. PSI is powered by a machine learning model trained on consumer-permissioned data. PSI provides a risk assessment, which includes a real-time balance check, predictive risk scores forecasting a consumer’s likelihood of having sufficient funds over a 10-day period, a real-time score predicting the likelihood of an unauthorized return, and risk attributes to explain and enhance decisioning. This product may not be used for uses subject to the FCRA.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generatePaymentSuccessIndicatorsTest() throws ApiException {
        String customerId = null;
        String accountId = null;
        PaymentSuccessIndicatorsProperties paymentSuccessIndicatorsProperties = null;
        PaymentSuccessIndicators response = api.generatePaymentSuccessIndicators(customerId, accountId, paymentSuccessIndicatorsProperties);
        // TODO: test validations
    }

    /**
     * Get FCRA Payment Success Indicator (Legacy)
     *
     * Payment Success Indicator (PSI) allows the user to evaluate the likelihood of a specific ACH transaction resulting in an insufficient funds return (NSF). PSI is powered by a machine learning model trained on Finicity’s consumer-permissioned data network. PSI provides a risk assessment, which includes a real-time balance check, a predictive risk score for the up to the next 9 days, and 8 risk attributes to explain and enhance decisioning. Provision and use of this report is subject to all applicable obligations of the FCRA and any applicable analogous state law. This product may only be used for the stated permissible purpose under the FCRA.    _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getFCRAPaymentSuccessIndicatorTest() throws ApiException {
        String customerId = null;
        String accountId = null;
        BigDecimal settlementAmount = null;
        LocalDate settleByDate = null;
        String purposeCode = null;
        PaymentSuccessIndicator response = api.getFCRAPaymentSuccessIndicator(customerId, accountId, settlementAmount, settleByDate, purposeCode);
        // TODO: test validations
    }

    /**
     * Get FCRA Payment Success Indicators by Pay Request ID
     *
     * Get the FCRA Payment Success Indicator scores that have been generated by a previous call to Generate FCRA Payment Success Indicators. _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getFcraPaymentSuccessIndicatorsTest() throws ApiException {
        String customerId = null;
        String accountId = null;
        String payRequestId = null;
        Boolean includeReasons = null;
        FcraPaymentSuccessIndicators response = api.getFcraPaymentSuccessIndicators(customerId, accountId, payRequestId, includeReasons);
        // TODO: test validations
    }

    /**
     * Get Non-FCRA Payment Success Indicator (Legacy)
     *
     * Payment Success Indicator (PSI) is a Payment Intelligence solution that uses Financial Institution (FI) data to help payment originators evaluate a consumer&#39;s ability to pay now and in the future within a given time period. PSI is for payment originators to assess a consumer&#39;s real-time FI account balance and historical FI account activities to help minimize ACH declines and enable payment originators to gracefully transition to alternative payment methods or schedules when payment settlement using ACH / Account-based payment is less likely. PSI may not be used for credit or insurance underwriting, employment or rental screening, or any other purpose(s) that would implicate the Fair Credit Reporting Act or other consumer reporting law.    _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPaymentSuccessIndicatorTest() throws ApiException {
        String customerId = null;
        String accountId = null;
        BigDecimal settlementAmount = null;
        LocalDate settleByDate = null;
        PaymentSuccessIndicator response = api.getPaymentSuccessIndicator(customerId, accountId, settlementAmount, settleByDate);
        // TODO: test validations
    }

    /**
     * Get Non-FCRA Payment Success Indicators by Pay Request ID
     *
     * Get the Non-FCRA Payment Success Indicator scores that have been generated by a previous call to Generate Payment Success Indicators.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPaymentSuccessIndicatorsTest() throws ApiException {
        String customerId = null;
        String accountId = null;
        String payRequestId = null;
        Boolean includeReasons = null;
        PaymentSuccessIndicators response = api.getPaymentSuccessIndicators(customerId, accountId, payRequestId, includeReasons);
        // TODO: test validations
    }

}
