/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.AnalyticsReportAck;
import org.openapitools.client.model.AnalyticsReportConstraints;
import org.openapitools.client.model.ErrorMessage;
import org.openapitools.client.model.SecurityFreezeErrorMessage;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PaymentHistoryReportApi
 */
@Disabled
public class PaymentHistoryReportApiTest {

    private final PaymentHistoryReportApi api = new PaymentHistoryReportApi();

    /**
     * Generate Payment History Report for the customer - Business
     *
     * Generate a Payment History Report for a given customer. This service retrieves up to two years of transaction history from connected accounts.  Payment History along with payment risk score provides the financial history and risk score based on a customer&#39;s financial history.  Before calling this API, A consumer or business may need to be created for the given customer ID based on the user type (see Consumer/Business APIs).  If no account type of checking, money market, or savings is found, the service will return HTTP 400 Bad Request.  This is a premium service, billable per every successful API call for non-testing customers. A successful call to this API will generate an analytics report which can be retrieved via Get Report by Customer or Get Report by Consumer.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generatePaymentHistoryReportTest() throws ApiException {
        String customerId = null;
        String userType = null;
        AnalyticsReportConstraints analyticsReportConstraints = null;
        String callbackUrl = null;
        AnalyticsReportAck response = api.generatePaymentHistoryReport(customerId, userType, analyticsReportConstraints, callbackUrl);
        // TODO: test validations
    }

}
