/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.BillingResellerReport;
import org.openapitools.client.model.ErrorMessage;
import org.openapitools.client.model.Lender;
import org.openapitools.client.model.Report;
import org.openapitools.client.model.ReportSummaries;
import org.openapitools.client.model.SecurityFreezeErrorMessage;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ReportsApi
 */
@Disabled
public class ReportsApiTest {

    private final ReportsApi api = new ReportsApi();

    /**
     * Get Report by Consumer and ID
     *
     * Get a report that has been generated by a previous call to one of the Generate Report services.  The report&#39;s &#x60;status&#x60; field contains \&quot;inProgress\&quot;, \&quot;failure\&quot;, or \&quot;success\&quot;. If the status shows \&quot;inProgress\&quot;, the client app should wait 20 seconds and then call this API again.  Report data can either be retrieved as a JSON document or a PDF file.  To specify the format required, set the _Accept request header_ to either **application/json** or **application/pdf**. If neither is set, the report format will be returned as a JSON document.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getReportByConsumerTest() throws ApiException {
        String consumerId = null;
        String reportId = null;
        String purpose = null;
        String onBehalfOf = null;
        Report response = api.getReportByConsumer(consumerId, reportId, purpose, onBehalfOf);
        // TODO: test validations
    }

    /**
     * Get Report by Customer and ID
     *
     * Get a report that has been generated by a previous call to one of the Generate Report services.  The report&#39;s &#x60;status&#x60; field contains \&quot;inProgress\&quot;, \&quot;failure\&quot;, or \&quot;success\&quot;. If the status shows \&quot;inProgress\&quot;, the client app should wait 20 seconds and then call this API again.  Report data can either be retrieved as a JSON document or a PDF file.  To specify the format required, set the _Accept request header_ to either **application/json** or **application/pdf**. If neither is set, the report format will be returned as a JSON document.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getReportByCustomerTest() throws ApiException {
        String customerId = null;
        String reportId = null;
        String onBehalfOf = null;
        String purpose = null;
        Report response = api.getReportByCustomer(customerId, reportId, onBehalfOf, purpose);
        // TODO: test validations
    }

    /**
     * Get Reports by Consumer ID
     *
     * Get all reports that have been generated by previous calls to Generate Report services for the given consumer.  The &#x60;status&#x60; fields in the returned list contain \&quot;inProgress\&quot;, \&quot;failure\&quot;, or \&quot;success\&quot;. If the status shows \&quot;inProgress\&quot;, the client app should wait 20 seconds and then call this API again.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getReportsByConsumerIdTest() throws ApiException {
        String consumerId = null;
        String purpose = null;
        ReportSummaries response = api.getReportsByConsumerId(consumerId, purpose);
        // TODO: test validations
    }

    /**
     * Get Reports by Customer ID
     *
     * Get all reports that have been generated by previous calls to Generate Report services for the given customer.  The &#x60;status&#x60; fields in the returned list contain \&quot;inProgress\&quot;, \&quot;failure\&quot;, or \&quot;success\&quot;. If the status shows \&quot;inProgress\&quot;, the client app should wait 20 seconds and then call this API again.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getReportsByCustomerIdTest() throws ApiException {
        String customerId = null;
        String purpose = null;
        ReportSummaries response = api.getReportsByCustomerId(customerId, purpose);
        // TODO: test validations
    }

    /**
     * Get billing summary for partner
     *
     * Use the Partner ID to fetch all reports generated by a partner. A partner can get their own reports and a reseller partner can get the reports for their customer’s partner account as long as the partner is set up with them as the reseller.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getResellerBillingReportTest() throws ApiException {
        String partnerId = null;
        Integer startDate = null;
        Integer endDate = null;
        Integer size = null;
        Integer page = null;
        Boolean viewTestingReports = null;
        BillingResellerReport response = api.getResellerBillingReport(partnerId, startDate, endDate, size, page, viewTestingReports);
        // TODO: test validations
    }

    /**
     * Report Reissue
     *
     *  Report Reissue is a billable service that enables authorized third parties - such as investors, mortgage insurers, QC agencies, and loan management systems - to securely access an existing CRA report originally generated by another Mastercard partner.  To retrieve a report, the requesting partner must provide the report ID which should be obtained from the partner who originally generated the report and the permissible purpose code which should match the original purpose the report was generated for. Note: This is not required today but will be changed to be required by April 30, 2026. Report data can either be retrieved as a JSON document or a PDF file. To specify the format required, set the Accept request header to either application/json or application/pdf. If neither is set, the report format will be returned as a JSON document.   _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void reportReissueTest() throws ApiException {
        String reportId = null;
        Lender lender = null;
        Report response = api.reportReissue(reportId, lender);
        // TODO: test validations
    }

}
