/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.EnrichTransactionsPayload;
import org.openapitools.client.model.EnrichedTransactions;
import org.openapitools.client.model.ErrorMessage;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TransactionDataEnrichmentApi
 */
@Disabled
public class TransactionDataEnrichmentApiTest {

    private final TransactionDataEnrichmentApi api = new TransactionDataEnrichmentApi();

    /**
     * Performs enrichment of the provided transactions
     *
     * The operation processes the enclosed transactions for enrichment with categorization and entity recognition. Accepts a batch of 1000 transactions.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void enrichTransactionsTest() throws ApiException {
        EnrichTransactionsPayload enrichTransactionsPayload = null;
        EnrichedTransactions response = api.enrichTransactions(enrichTransactionsPayload);
        // TODO: test validations
    }

}
