/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.DepositSwitchDetails;
import org.openapitools.client.model.DepositSwitchesSummary;
import org.openapitools.client.model.ErrorMessage;
import org.openapitools.client.model.PaySwitchDetails;
import org.openapitools.client.model.PaySwitchesSummary;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TransferApi
 */
@Disabled
public class TransferApiTest {

    private final TransferApi api = new TransferApi();

    /**
     * Get Deposit Switches by Customer ID
     *
     * Retrieve summary of deposit switches performed by given customer ID. _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllDepositSwitchesTest() throws ApiException {
        String customerId = null;
        DepositSwitchesSummary response = api.getAllDepositSwitches(customerId);
        // TODO: test validations
    }

    /**
     * Get Pay Switches by Customer ID
     *
     * Retrieve summary of bill pay switches performed by given customer ID. _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllPaySwitchesTest() throws ApiException {
        String customerId = null;
        PaySwitchesSummary response = api.getAllPaySwitches(customerId);
        // TODO: test validations
    }

    /**
     * Get Pay Switch by ID
     *
     * Retrieve bill pay switch details by switch ID. _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getBillPaySwitchDetailsTest() throws ApiException {
        String customerId = null;
        String switchId = null;
        PaySwitchDetails response = api.getBillPaySwitchDetails(customerId, switchId);
        // TODO: test validations
    }

    /**
     * Get Deposit Switch by ID
     *
     * Retrieve deposit switch details by switch ID. _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDepositSwitchDetailsTest() throws ApiException {
        String customerId = null;
        String switchId = null;
        DepositSwitchDetails response = api.getDepositSwitchDetails(customerId, switchId);
        // TODO: test validations
    }

}
