/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AccountOwnerDocumentation;
import org.openapitools.client.model.AccountOwnerIdentityInsights;
import org.openapitools.client.model.AccountOwnerVerificationMatchingAddress;
import org.openapitools.client.model.AccountOwnerVerificationMatchingEmail;
import org.openapitools.client.model.AccountOwnerVerificationPhone;
import org.openapitools.client.model.NameScore;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AccountOwnerVerificationMatchingDetails
 */
public class AccountOwnerVerificationMatchingDetailsTest {
    private final AccountOwnerVerificationMatchingDetails model = new AccountOwnerVerificationMatchingDetails();

    /**
     * Model tests for AccountOwnerVerificationMatchingDetails
     */
    @Test
    public void testAccountOwnerVerificationMatchingDetails() {
        // TODO: test AccountOwnerVerificationMatchingDetails
    }

    /**
     * Test the property 'relationship'
     */
    @Test
    public void relationshipTest() {
        // TODO: test relationship
    }

    /**
     * Test the property 'ownerName'
     */
    @Test
    public void ownerNameTest() {
        // TODO: test ownerName
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'middleName'
     */
    @Test
    public void middleNameTest() {
        // TODO: test middleName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'suffix'
     */
    @Test
    public void suffixTest() {
        // TODO: test suffix
    }

    /**
     * Test the property 'nameScores'
     */
    @Test
    public void nameScoresTest() {
        // TODO: test nameScores
    }

    /**
     * Test the property 'nameClassification'
     */
    @Test
    public void nameClassificationTest() {
        // TODO: test nameClassification
    }

    /**
     * Test the property 'nameClassificationconfidencescore'
     */
    @Test
    public void nameClassificationconfidencescoreTest() {
        // TODO: test nameClassificationconfidencescore
    }

    /**
     * Test the property 'addresses'
     */
    @Test
    public void addressesTest() {
        // TODO: test addresses
    }

    /**
     * Test the property 'emails'
     */
    @Test
    public void emailsTest() {
        // TODO: test emails
    }

    /**
     * Test the property 'phones'
     */
    @Test
    public void phonesTest() {
        // TODO: test phones
    }

    /**
     * Test the property 'documentations'
     */
    @Test
    public void documentationsTest() {
        // TODO: test documentations
    }

    /**
     * Test the property 'identityInsights'
     */
    @Test
    public void identityInsightsTest() {
        // TODO: test identityInsights
    }

}
