/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.StateAttribute;
import org.openapitools.client.model.StreamModel;
import org.openapitools.client.model.TransactionalAttribute;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AccountAnalytics
 */
public class AccountAnalyticsTest {
    private final AccountAnalytics model = new AccountAnalytics();

    /**
     * Model tests for AccountAnalytics
     */
    @Test
    public void testAccountAnalytics() {
        // TODO: test AccountAnalytics
    }

    /**
     * Test the property 'transactionalAttributes'
     */
    @Test
    public void transactionalAttributesTest() {
        // TODO: test transactionalAttributes
    }

    /**
     * Test the property 'stateAttributes'
     */
    @Test
    public void stateAttributesTest() {
        // TODO: test stateAttributes
    }

    /**
     * Test the property 'streams'
     */
    @Test
    public void streamsTest() {
        // TODO: test streams
    }

}
