/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.EmailScores;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AccountOwnerVerificationMatchingEmail
 */
public class AccountOwnerVerificationMatchingEmailTest {
    private final AccountOwnerVerificationMatchingEmail model = new AccountOwnerVerificationMatchingEmail();

    /**
     * Model tests for AccountOwnerVerificationMatchingEmail
     */
    @Test
    public void testAccountOwnerVerificationMatchingEmail() {
        // TODO: test AccountOwnerVerificationMatchingEmail
    }

    /**
     * Test the property 'isPrimary'
     */
    @Test
    public void isPrimaryTest() {
        // TODO: test isPrimary
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'emailType'
     */
    @Test
    public void emailTypeTest() {
        // TODO: test emailType
    }

    /**
     * Test the property 'emailScores'
     */
    @Test
    public void emailScoresTest() {
        // TODO: test emailScores
    }

}
