/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AccountDetailsTxBased
 */
public class AccountDetailsTxBasedTest {
    private final AccountDetailsTxBased model = new AccountDetailsTxBased();

    /**
     * Model tests for AccountDetailsTxBased
     */
    @Test
    public void testAccountDetailsTxBased() {
        // TODO: test AccountDetailsTxBased
    }

    /**
     * Test the property 'interestMarginBalance'
     */
    @Test
    public void interestMarginBalanceTest() {
        // TODO: test interestMarginBalance
    }

    /**
     * Test the property 'availableCashBalance'
     */
    @Test
    public void availableCashBalanceTest() {
        // TODO: test availableCashBalance
    }

    /**
     * Test the property 'vestedBalance'
     */
    @Test
    public void vestedBalanceTest() {
        // TODO: test vestedBalance
    }

    /**
     * Test the property 'currentLoanBalance'
     */
    @Test
    public void currentLoanBalanceTest() {
        // TODO: test currentLoanBalance
    }

    /**
     * Test the property 'availableBalanceAmount'
     */
    @Test
    public void availableBalanceAmountTest() {
        // TODO: test availableBalanceAmount
    }

    /**
     * Test the property 'marginBalance'
     */
    @Test
    public void marginBalanceTest() {
        // TODO: test marginBalance
    }

    /**
     * Test the property 'currentBalance'
     */
    @Test
    public void currentBalanceTest() {
        // TODO: test currentBalance
    }

}
