/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AnnualIncome
 */
public class AnnualIncomeTest {
    private final AnnualIncome model = new AnnualIncome();

    /**
     * Model tests for AnnualIncome
     */
    @Test
    public void testAnnualIncome() {
        // TODO: test AnnualIncome
    }

    /**
     * Test the property 'year'
     */
    @Test
    public void yearTest() {
        // TODO: test year
    }

    /**
     * Test the property 'grossPayAmountYTD'
     */
    @Test
    public void grossPayAmountYTDTest() {
        // TODO: test grossPayAmountYTD
    }

    /**
     * Test the property 'netPayAmountYTD'
     */
    @Test
    public void netPayAmountYTDTest() {
        // TODO: test netPayAmountYTD
    }

    /**
     * Test the property 'basePayAmountYTD'
     */
    @Test
    public void basePayAmountYTDTest() {
        // TODO: test basePayAmountYTD
    }

    /**
     * Test the property 'overtimePayAmountYTD'
     */
    @Test
    public void overtimePayAmountYTDTest() {
        // TODO: test overtimePayAmountYTD
    }

    /**
     * Test the property 'otherPayAmountYTD'
     */
    @Test
    public void otherPayAmountYTDTest() {
        // TODO: test otherPayAmountYTD
    }

    /**
     * Test the property 'commissionPayAmountYTD'
     */
    @Test
    public void commissionPayAmountYTDTest() {
        // TODO: test commissionPayAmountYTD
    }

}
