/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Application
 */
public class ApplicationTest {
    private final Application model = new Application();

    /**
     * Model tests for Application
     */
    @Test
    public void testApplication() {
        // TODO: test Application
    }

    /**
     * Test the property 'appDescription'
     */
    @Test
    public void appDescriptionTest() {
        // TODO: test appDescription
    }

    /**
     * Test the property 'appName'
     */
    @Test
    public void appNameTest() {
        // TODO: test appName
    }

    /**
     * Test the property 'appUrl'
     */
    @Test
    public void appUrlTest() {
        // TODO: test appUrl
    }

    /**
     * Test the property 'ownerAddressLine1'
     */
    @Test
    public void ownerAddressLine1Test() {
        // TODO: test ownerAddressLine1
    }

    /**
     * Test the property 'ownerAddressLine2'
     */
    @Test
    public void ownerAddressLine2Test() {
        // TODO: test ownerAddressLine2
    }

    /**
     * Test the property 'ownerCity'
     */
    @Test
    public void ownerCityTest() {
        // TODO: test ownerCity
    }

    /**
     * Test the property 'ownerCountry'
     */
    @Test
    public void ownerCountryTest() {
        // TODO: test ownerCountry
    }

    /**
     * Test the property 'ownerName'
     */
    @Test
    public void ownerNameTest() {
        // TODO: test ownerName
    }

    /**
     * Test the property 'ownerPostalCode'
     */
    @Test
    public void ownerPostalCodeTest() {
        // TODO: test ownerPostalCode
    }

    /**
     * Test the property 'ownerState'
     */
    @Test
    public void ownerStateTest() {
        // TODO: test ownerState
    }

    /**
     * Test the property 'image'
     */
    @Test
    public void imageTest() {
        // TODO: test image
    }

}
