/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AppStatus;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AppStatuses
 */
public class AppStatusesTest {
    private final AppStatuses model = new AppStatuses();

    /**
     * Model tests for AppStatuses
     */
    @Test
    public void testAppStatuses() {
        // TODO: test AppStatuses
    }

    /**
     * Test the property 'totalRecords'
     */
    @Test
    public void totalRecordsTest() {
        // TODO: test totalRecords
    }

    /**
     * Test the property 'totalPages'
     */
    @Test
    public void totalPagesTest() {
        // TODO: test totalPages
    }

    /**
     * Test the property 'pageNumber'
     */
    @Test
    public void pageNumberTest() {
        // TODO: test pageNumber
    }

    /**
     * Test the property 'numberOfRecordsPerPage'
     */
    @Test
    public void numberOfRecordsPerPageTest() {
        // TODO: test numberOfRecordsPerPage
    }

    /**
     * Test the property 'applications'
     */
    @Test
    public void applicationsTest() {
        // TODO: test applications
    }

}
