/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AvailableEventConditionalSubscription
 */
public class AvailableEventConditionalSubscriptionTest {
    private final AvailableEventConditionalSubscription model = new AvailableEventConditionalSubscription();

    /**
     * Model tests for AvailableEventConditionalSubscription
     */
    @Test
    public void testAvailableEventConditionalSubscription() {
        // TODO: test AvailableEventConditionalSubscription
    }

    /**
     * Test the property 'applicable'
     */
    @Test
    public void applicableTest() {
        // TODO: test applicable
    }

    /**
     * Test the property 'fields'
     */
    @Test
    public void fieldsTest() {
        // TODO: test fields
    }

    /**
     * Test the property 'mandatory'
     */
    @Test
    public void mandatoryTest() {
        // TODO: test mandatory
    }

}
