/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AvailableBalance
 */
public class AvailableBalanceTest {
    private final AvailableBalance model = new AvailableBalance();

    /**
     * Model tests for AvailableBalance
     */
    @Test
    public void testAvailableBalance() {
        // TODO: test AvailableBalance
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'realAccountNumberLast4'
     */
    @Test
    public void realAccountNumberLast4Test() {
        // TODO: test realAccountNumberLast4
    }

    /**
     * Test the property 'availableBalance'
     */
    @Test
    public void availableBalanceTest() {
        // TODO: test availableBalance
    }

    /**
     * Test the property 'availableBalanceDate'
     */
    @Test
    public void availableBalanceDateTest() {
        // TODO: test availableBalanceDate
    }

    /**
     * Test the property 'clearedBalance'
     */
    @Test
    public void clearedBalanceTest() {
        // TODO: test clearedBalance
    }

    /**
     * Test the property 'clearedBalanceDate'
     */
    @Test
    public void clearedBalanceDateTest() {
        // TODO: test clearedBalanceDate
    }

    /**
     * Test the property 'aggregationStatusCode'
     */
    @Test
    public void aggregationStatusCodeTest() {
        // TODO: test aggregationStatusCode
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

}
