/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.BalanceAnalyticsMetrics;
import org.openapitools.client.model.ObbCurrentReportRequestDetails;
import org.openapitools.client.model.ObbDataAvailability;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BalanceAnalyticsBusinessSummary
 */
public class BalanceAnalyticsBusinessSummaryTest {
    private final BalanceAnalyticsBusinessSummary model = new BalanceAnalyticsBusinessSummary();

    /**
     * Model tests for BalanceAnalyticsBusinessSummary
     */
    @Test
    public void testBalanceAnalyticsBusinessSummary() {
        // TODO: test BalanceAnalyticsBusinessSummary
    }

    /**
     * Test the property 'balanceAnalyticsMetrics'
     */
    @Test
    public void balanceAnalyticsMetricsTest() {
        // TODO: test balanceAnalyticsMetrics
    }

    /**
     * Test the property 'currentReportRequest'
     */
    @Test
    public void currentReportRequestTest() {
        // TODO: test currentReportRequest
    }

    /**
     * Test the property 'historicDataAvailability'
     */
    @Test
    public void historicDataAvailabilityTest() {
        // TODO: test historicDataAvailability
    }

}
