/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AnalyticsReportConstraintsOut;
import org.openapitools.client.model.AnalyticsReportData;
import org.openapitools.client.model.CashFlowReportConstraintsOut;
import org.openapitools.client.model.FindTransactionConstraintsInner;
import org.openapitools.client.model.PayStatementData;
import org.openapitools.client.model.PayStatementReportConstraints;
import org.openapitools.client.model.PayrollDataOut;
import org.openapitools.client.model.PayrollReportConstraintsOut;
import org.openapitools.client.model.PrequalificationReportConstraintsOut;
import org.openapitools.client.model.ReportCustomField;
import org.openapitools.client.model.StatementData;
import org.openapitools.client.model.StatementReportConstraints;
import org.openapitools.client.model.TransactionsReportConstraintsOut;
import org.openapitools.client.model.VOAReportConstraintsOut;
import org.openapitools.client.model.VOAWithIncomeReportConstraintsOut;
import org.openapitools.client.model.VOETransactionsReportConstraintsOut;
import org.openapitools.client.model.VOIEReportConstraints;
import org.openapitools.client.model.VOIEWithInterviewData;
import org.openapitools.client.model.VOIEWithStatementData;
import org.openapitools.client.model.VOIEWithTXVerifyReportConstraintsOut;
import org.openapitools.client.model.VOIReportConstraintsOut;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BaseReportAckConstraints
 */
public class BaseReportAckConstraintsTest {
    private final BaseReportAckConstraints model = new BaseReportAckConstraints();

    /**
     * Model tests for BaseReportAckConstraints
     */
    @Test
    public void testBaseReportAckConstraints() {
        // TODO: test BaseReportAckConstraints
    }

    /**
     * Test the property 'analyticsReportData'
     */
    @Test
    public void analyticsReportDataTest() {
        // TODO: test analyticsReportData
    }

    /**
     * Test the property 'accountIds'
     */
    @Test
    public void accountIdsTest() {
        // TODO: test accountIds
    }

    /**
     * Test the property 'reportCustomFields'
     */
    @Test
    public void reportCustomFieldsTest() {
        // TODO: test reportCustomFields
    }

    /**
     * Test the property 'fromDate'
     */
    @Test
    public void fromDateTest() {
        // TODO: test fromDate
    }

    /**
     * Test the property 'showNsf'
     */
    @Test
    public void showNsfTest() {
        // TODO: test showNsf
    }

    /**
     * Test the property 'incomeStreamConfidenceMinimum'
     */
    @Test
    public void incomeStreamConfidenceMinimumTest() {
        // TODO: test incomeStreamConfidenceMinimum
    }

    /**
     * Test the property 'voieWithInterviewData'
     */
    @Test
    public void voieWithInterviewDataTest() {
        // TODO: test voieWithInterviewData
    }

    /**
     * Test the property 'voieWithStatementData'
     */
    @Test
    public void voieWithStatementDataTest() {
        // TODO: test voieWithStatementData
    }

    /**
     * Test the property 'statementReportData'
     */
    @Test
    public void statementReportDataTest() {
        // TODO: test statementReportData
    }

    /**
     * Test the property 'toDate'
     */
    @Test
    public void toDateTest() {
        // TODO: test toDate
    }

    /**
     * Test the property 'includePending'
     */
    @Test
    public void includePendingTest() {
        // TODO: test includePending
    }

    /**
     * Test the property 'findTransaction'
     */
    @Test
    public void findTransactionTest() {
        // TODO: test findTransaction
    }

    /**
     * Test the property 'incomeFromDate'
     */
    @Test
    public void incomeFromDateTest() {
        // TODO: test incomeFromDate
    }

    /**
     * Test the property 'voaiPdfDepositView'
     */
    @Test
    public void voaiPdfDepositViewTest() {
        // TODO: test voaiPdfDepositView
    }

    /**
     * Test the property 'payrollData'
     */
    @Test
    public void payrollDataTest() {
        // TODO: test payrollData
    }

    /**
     * Test the property 'payStatementsFromDate'
     */
    @Test
    public void payStatementsFromDateTest() {
        // TODO: test payStatementsFromDate
    }

    /**
     * Test the property 'reportId'
     */
    @Test
    public void reportIdTest() {
        // TODO: test reportId
    }

    /**
     * Test the property 'paystatementReport'
     */
    @Test
    public void paystatementReportTest() {
        // TODO: test paystatementReport
    }

}
