/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ReportCustomField;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BillingReport
 */
public class BillingReportTest {
    private final BillingReport model = new BillingReport();

    /**
     * Model tests for BillingReport
     */
    @Test
    public void testBillingReport() {
        // TODO: test BillingReport
    }

    /**
     * Test the property 'reseller'
     */
    @Test
    public void resellerTest() {
        // TODO: test reseller
    }

    /**
     * Test the property 'resellerProvider'
     */
    @Test
    public void resellerProviderTest() {
        // TODO: test resellerProvider
    }

    /**
     * Test the property 'platformProvider'
     */
    @Test
    public void platformProviderTest() {
        // TODO: test platformProvider
    }

    /**
     * Test the property 'customerId'
     */
    @Test
    public void customerIdTest() {
        // TODO: test customerId
    }

    /**
     * Test the property 'consumerId'
     */
    @Test
    public void consumerIdTest() {
        // TODO: test consumerId
    }

    /**
     * Test the property 'consumerSsn'
     */
    @Test
    public void consumerSsnTest() {
        // TODO: test consumerSsn
    }

    /**
     * Test the property 'consumerCustomId'
     */
    @Test
    public void consumerCustomIdTest() {
        // TODO: test consumerCustomId
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'lastFourReportId'
     */
    @Test
    public void lastFourReportIdTest() {
        // TODO: test lastFourReportId
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    public void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'reportType'
     */
    @Test
    public void reportTypeTest() {
        // TODO: test reportType
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'reportCustomFields'
     */
    @Test
    public void reportCustomFieldsTest() {
        // TODO: test reportCustomFields
    }

}
