/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Branding
 */
public class BrandingTest {
    private final Branding model = new Branding();

    /**
     * Model tests for Branding
     */
    @Test
    public void testBranding() {
        // TODO: test Branding
    }

    /**
     * Test the property 'logo'
     */
    @Test
    public void logoTest() {
        // TODO: test logo
    }

    /**
     * Test the property 'alternateLogo'
     */
    @Test
    public void alternateLogoTest() {
        // TODO: test alternateLogo
    }

    /**
     * Test the property 'icon'
     */
    @Test
    public void iconTest() {
        // TODO: test icon
    }

    /**
     * Test the property 'primaryColor'
     */
    @Test
    public void primaryColorTest() {
        // TODO: test primaryColor
    }

    /**
     * Test the property 'tile'
     */
    @Test
    public void tileTest() {
        // TODO: test tile
    }

}
