/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CashFlowMonthlyCashFlowBalances
 */
public class CashFlowMonthlyCashFlowBalancesTest {
    private final CashFlowMonthlyCashFlowBalances model = new CashFlowMonthlyCashFlowBalances();

    /**
     * Model tests for CashFlowMonthlyCashFlowBalances
     */
    @Test
    public void testCashFlowMonthlyCashFlowBalances() {
        // TODO: test CashFlowMonthlyCashFlowBalances
    }

    /**
     * Test the property 'month'
     */
    @Test
    public void monthTest() {
        // TODO: test month
    }

    /**
     * Test the property 'minDailyBalance'
     */
    @Test
    public void minDailyBalanceTest() {
        // TODO: test minDailyBalance
    }

    /**
     * Test the property 'maxDailyBalance'
     */
    @Test
    public void maxDailyBalanceTest() {
        // TODO: test maxDailyBalance
    }

    /**
     * Test the property 'averageDailyBalance'
     */
    @Test
    public void averageDailyBalanceTest() {
        // TODO: test averageDailyBalance
    }

    /**
     * Test the property 'standardDeviationOfDailyBalance'
     */
    @Test
    public void standardDeviationOfDailyBalanceTest() {
        // TODO: test standardDeviationOfDailyBalance
    }

    /**
     * Test the property 'numberOfDaysNegativeBalance'
     */
    @Test
    public void numberOfDaysNegativeBalanceTest() {
        // TODO: test numberOfDaysNegativeBalance
    }

    /**
     * Test the property 'numberOfDaysPositiveBalance'
     */
    @Test
    public void numberOfDaysPositiveBalanceTest() {
        // TODO: test numberOfDaysPositiveBalance
    }

}
