/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CashFlowActivityWithdrawalsDebits
 */
public class CashFlowActivityWithdrawalsDebitsTest {
    private final CashFlowActivityWithdrawalsDebits model = new CashFlowActivityWithdrawalsDebits();

    /**
     * Model tests for CashFlowActivityWithdrawalsDebits
     */
    @Test
    public void testCashFlowActivityWithdrawalsDebits() {
        // TODO: test CashFlowActivityWithdrawalsDebits
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'transactionDescription'
     */
    @Test
    public void transactionDescriptionTest() {
        // TODO: test transactionDescription
    }

    /**
     * Test the property 'withdrawalsDebits'
     */
    @Test
    public void withdrawalsDebitsTest() {
        // TODO: test withdrawalsDebits
    }

}
