/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ObbDateRangeAndAmount;
import org.openapitools.client.model.ObbDateRangeAndCount;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CashFlowOutflowAttributes
 */
public class CashFlowOutflowAttributesTest {
    private final CashFlowOutflowAttributes model = new CashFlowOutflowAttributes();

    /**
     * Model tests for CashFlowOutflowAttributes
     */
    @Test
    public void testCashFlowOutflowAttributes() {
        // TODO: test CashFlowOutflowAttributes
    }

    /**
     * Test the property 'averageWithdrawalByMonthForTheReportTimePeriod'
     */
    @Test
    public void averageWithdrawalByMonthForTheReportTimePeriodTest() {
        // TODO: test averageWithdrawalByMonthForTheReportTimePeriod
    }

    /**
     * Test the property 'countWithdrawalsByMonthForTheReportTimePeriod'
     */
    @Test
    public void countWithdrawalsByMonthForTheReportTimePeriodTest() {
        // TODO: test countWithdrawalsByMonthForTheReportTimePeriod
    }

    /**
     * Test the property 'historicCountOfWithdrawalTransactions'
     */
    @Test
    public void historicCountOfWithdrawalTransactionsTest() {
        // TODO: test historicCountOfWithdrawalTransactions
    }

    /**
     * Test the property 'historicSumOfWithdrawals'
     */
    @Test
    public void historicSumOfWithdrawalsTest() {
        // TODO: test historicSumOfWithdrawals
    }

    /**
     * Test the property 'maximumWithdrawalByMonthForTheReportTimePeriod'
     */
    @Test
    public void maximumWithdrawalByMonthForTheReportTimePeriodTest() {
        // TODO: test maximumWithdrawalByMonthForTheReportTimePeriod
    }

    /**
     * Test the property 'minimumWithdrawalByMonthForTheReportTimePeriod'
     */
    @Test
    public void minimumWithdrawalByMonthForTheReportTimePeriodTest() {
        // TODO: test minimumWithdrawalByMonthForTheReportTimePeriod
    }

    /**
     * Test the property 'sumWithdrawalsByMonthForTheReportTimePeriod'
     */
    @Test
    public void sumWithdrawalsByMonthForTheReportTimePeriodTest() {
        // TODO: test sumWithdrawalsByMonthForTheReportTimePeriod
    }

}
