/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.CashFlowMonthlyCashFlowDebitSummaries;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CashFlowCashFlowDebitSummary
 */
public class CashFlowCashFlowDebitSummaryTest {
    private final CashFlowCashFlowDebitSummary model = new CashFlowCashFlowDebitSummary();

    /**
     * Model tests for CashFlowCashFlowDebitSummary
     */
    @Test
    public void testCashFlowCashFlowDebitSummary() {
        // TODO: test CashFlowCashFlowDebitSummary
    }

    /**
     * Test the property 'monthlyCashFlowDebitSummaries'
     */
    @Test
    public void monthlyCashFlowDebitSummariesTest() {
        // TODO: test monthlyCashFlowDebitSummaries
    }

    /**
     * Test the property 'twelveMonthDebitTotal'
     */
    @Test
    public void twelveMonthDebitTotalTest() {
        // TODO: test twelveMonthDebitTotal
    }

    /**
     * Test the property 'twelveMonthDebitTotalLessTransfers'
     */
    @Test
    public void twelveMonthDebitTotalLessTransfersTest() {
        // TODO: test twelveMonthDebitTotalLessTransfers
    }

    /**
     * Test the property 'sixMonthDebitTotal'
     */
    @Test
    public void sixMonthDebitTotalTest() {
        // TODO: test sixMonthDebitTotal
    }

    /**
     * Test the property 'sixMonthDebitTotalLessTransfers'
     */
    @Test
    public void sixMonthDebitTotalLessTransfersTest() {
        // TODO: test sixMonthDebitTotalLessTransfers
    }

    /**
     * Test the property 'twoMonthDebitTotal'
     */
    @Test
    public void twoMonthDebitTotalTest() {
        // TODO: test twoMonthDebitTotal
    }

    /**
     * Test the property 'twoMonthDebitTotalLessTransfers'
     */
    @Test
    public void twoMonthDebitTotalLessTransfersTest() {
        // TODO: test twoMonthDebitTotalLessTransfers
    }

}
