/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CashFlowMonthlyCashFlowCharacteristics
 */
public class CashFlowMonthlyCashFlowCharacteristicsTest {
    private final CashFlowMonthlyCashFlowCharacteristics model = new CashFlowMonthlyCashFlowCharacteristics();

    /**
     * Model tests for CashFlowMonthlyCashFlowCharacteristics
     */
    @Test
    public void testCashFlowMonthlyCashFlowCharacteristics() {
        // TODO: test CashFlowMonthlyCashFlowCharacteristics
    }

    /**
     * Test the property 'month'
     */
    @Test
    public void monthTest() {
        // TODO: test month
    }

    /**
     * Test the property 'totalCreditsLessTotalDebits'
     */
    @Test
    public void totalCreditsLessTotalDebitsTest() {
        // TODO: test totalCreditsLessTotalDebits
    }

    /**
     * Test the property 'totalCreditsLessTotalDebitsLessTransfers'
     */
    @Test
    public void totalCreditsLessTotalDebitsLessTransfersTest() {
        // TODO: test totalCreditsLessTotalDebitsLessTransfers
    }

    /**
     * Test the property 'averageTransactionAmount'
     */
    @Test
    public void averageTransactionAmountTest() {
        // TODO: test averageTransactionAmount
    }

}
