/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.CashFlowMonthlyCashFlowCreditSummaries;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CashFlowCashFlowCreditSummary
 */
public class CashFlowCashFlowCreditSummaryTest {
    private final CashFlowCashFlowCreditSummary model = new CashFlowCashFlowCreditSummary();

    /**
     * Model tests for CashFlowCashFlowCreditSummary
     */
    @Test
    public void testCashFlowCashFlowCreditSummary() {
        // TODO: test CashFlowCashFlowCreditSummary
    }

    /**
     * Test the property 'monthlyCashFlowCreditSummaries'
     */
    @Test
    public void monthlyCashFlowCreditSummariesTest() {
        // TODO: test monthlyCashFlowCreditSummaries
    }

    /**
     * Test the property 'twelveMonthCreditTotal'
     */
    @Test
    public void twelveMonthCreditTotalTest() {
        // TODO: test twelveMonthCreditTotal
    }

    /**
     * Test the property 'twelveMonthCreditTotalLessTransfers'
     */
    @Test
    public void twelveMonthCreditTotalLessTransfersTest() {
        // TODO: test twelveMonthCreditTotalLessTransfers
    }

    /**
     * Test the property 'sixMonthCreditTotal'
     */
    @Test
    public void sixMonthCreditTotalTest() {
        // TODO: test sixMonthCreditTotal
    }

    /**
     * Test the property 'sixMonthCreditTotalLessTransfers'
     */
    @Test
    public void sixMonthCreditTotalLessTransfersTest() {
        // TODO: test sixMonthCreditTotalLessTransfers
    }

    /**
     * Test the property 'twoMonthCreditTotal'
     */
    @Test
    public void twoMonthCreditTotalTest() {
        // TODO: test twoMonthCreditTotal
    }

    /**
     * Test the property 'twoMonthCreditTotalLessTransfers'
     */
    @Test
    public void twoMonthCreditTotalLessTransfersTest() {
        // TODO: test twoMonthCreditTotalLessTransfers
    }

}
