/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.CashFlowMonthlyCashFlowCharacteristicsSummaries;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CashFlowCashFlowCharacteristicsSummary
 */
public class CashFlowCashFlowCharacteristicsSummaryTest {
    private final CashFlowCashFlowCharacteristicsSummary model = new CashFlowCashFlowCharacteristicsSummary();

    /**
     * Model tests for CashFlowCashFlowCharacteristicsSummary
     */
    @Test
    public void testCashFlowCashFlowCharacteristicsSummary() {
        // TODO: test CashFlowCashFlowCharacteristicsSummary
    }

    /**
     * Test the property 'monthlyCashFlowCharacteristicsSummaries'
     */
    @Test
    public void monthlyCashFlowCharacteristicsSummariesTest() {
        // TODO: test monthlyCashFlowCharacteristicsSummaries
    }

    /**
     * Test the property 'averageMonthlyNet'
     */
    @Test
    public void averageMonthlyNetTest() {
        // TODO: test averageMonthlyNet
    }

    /**
     * Test the property 'averageMonthlyNetLessTransfers'
     */
    @Test
    public void averageMonthlyNetLessTransfersTest() {
        // TODO: test averageMonthlyNetLessTransfers
    }

    /**
     * Test the property 'twelveMonthTotalNet'
     */
    @Test
    public void twelveMonthTotalNetTest() {
        // TODO: test twelveMonthTotalNet
    }

    /**
     * Test the property 'twelveMonthTotalNetLessTransfers'
     */
    @Test
    public void twelveMonthTotalNetLessTransfersTest() {
        // TODO: test twelveMonthTotalNetLessTransfers
    }

    /**
     * Test the property 'sixMonthAverageTotalCreditsLessTotalDebits'
     */
    @Test
    public void sixMonthAverageTotalCreditsLessTotalDebitsTest() {
        // TODO: test sixMonthAverageTotalCreditsLessTotalDebits
    }

    /**
     * Test the property 'sixMonthAverageTotalCreditsLessTotalDebitsLessTransfers'
     */
    @Test
    public void sixMonthAverageTotalCreditsLessTotalDebitsLessTransfersTest() {
        // TODO: test sixMonthAverageTotalCreditsLessTotalDebitsLessTransfers
    }

    /**
     * Test the property 'twoMonthAverageTotalCreditsLessTotalDebits'
     */
    @Test
    public void twoMonthAverageTotalCreditsLessTotalDebitsTest() {
        // TODO: test twoMonthAverageTotalCreditsLessTotalDebits
    }

    /**
     * Test the property 'twoMonthAverageTotalCreditsLessTotalDebitsLessTransfers'
     */
    @Test
    public void twoMonthAverageTotalCreditsLessTotalDebitsLessTransfersTest() {
        // TODO: test twoMonthAverageTotalCreditsLessTotalDebitsLessTransfers
    }

}
