/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.InsufficientFundsTransaction;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CashFlowInsufficientFundsFees
 */
public class CashFlowInsufficientFundsFeesTest {
    private final CashFlowInsufficientFundsFees model = new CashFlowInsufficientFundsFees();

    /**
     * Model tests for CashFlowInsufficientFundsFees
     */
    @Test
    public void testCashFlowInsufficientFundsFees() {
        // TODO: test CashFlowInsufficientFundsFees
    }

    /**
     * Test the property 'countOfTransactionsForTheReportTimePeriod'
     */
    @Test
    public void countOfTransactionsForTheReportTimePeriodTest() {
        // TODO: test countOfTransactionsForTheReportTimePeriod
    }

    /**
     * Test the property 'sumOfTransactionsForTheReportTimePeriod'
     */
    @Test
    public void sumOfTransactionsForTheReportTimePeriodTest() {
        // TODO: test sumOfTransactionsForTheReportTimePeriod
    }

    /**
     * Test the property 'transactions'
     */
    @Test
    public void transactionsTest() {
        // TODO: test transactions
    }

}
