/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ChildInstitution;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CertifiedInstitution
 */
public class CertifiedInstitutionTest {
    private final CertifiedInstitution model = new CertifiedInstitution();

    /**
     * Model tests for CertifiedInstitution
     */
    @Test
    public void testCertifiedInstitution() {
        // TODO: test CertifiedInstitution
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'rssd'
     */
    @Test
    public void rssdTest() {
        // TODO: test rssd
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'transAgg'
     */
    @Test
    public void transAggTest() {
        // TODO: test transAgg
    }

    /**
     * Test the property 'ach'
     */
    @Test
    public void achTest() {
        // TODO: test ach
    }

    /**
     * Test the property 'stateAgg'
     */
    @Test
    public void stateAggTest() {
        // TODO: test stateAgg
    }

    /**
     * Test the property 'voi'
     */
    @Test
    public void voiTest() {
        // TODO: test voi
    }

    /**
     * Test the property 'voa'
     */
    @Test
    public void voaTest() {
        // TODO: test voa
    }

    /**
     * Test the property 'aha'
     */
    @Test
    public void ahaTest() {
        // TODO: test aha
    }

    /**
     * Test the property 'availBalance'
     */
    @Test
    public void availBalanceTest() {
        // TODO: test availBalance
    }

    /**
     * Test the property 'accountOwner'
     */
    @Test
    public void accountOwnerTest() {
        // TODO: test accountOwner
    }

    /**
     * Test the property 'studentLoanData'
     */
    @Test
    public void studentLoanDataTest() {
        // TODO: test studentLoanData
    }

    /**
     * Test the property 'loanPaymentDetails'
     */
    @Test
    public void loanPaymentDetailsTest() {
        // TODO: test loanPaymentDetails
    }

    /**
     * Test the property 'childInstitutions'
     */
    @Test
    public void childInstitutionsTest() {
        // TODO: test childInstitutions
    }

}
