/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ChildInstitution
 */
public class ChildInstitutionTest {
    private final ChildInstitution model = new ChildInstitution();

    /**
     * Model tests for ChildInstitution
     */
    @Test
    public void testChildInstitution() {
        // TODO: test ChildInstitution
    }

    /**
     * Test the property 'rssd'
     */
    @Test
    public void rssdTest() {
        // TODO: test rssd
    }

    /**
     * Test the property 'parentRSSD'
     */
    @Test
    public void parentRSSDTest() {
        // TODO: test parentRSSD
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'institutionId'
     */
    @Test
    public void institutionIdTest() {
        // TODO: test institutionId
    }

}
