/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ConsumerInfo
 */
public class ConsumerInfoTest {
    private final ConsumerInfo model = new ConsumerInfo();

    /**
     * Model tests for ConsumerInfo
     */
    @Test
    public void testConsumerInfo() {
        // TODO: test ConsumerInfo
    }

    /**
     * Test the property 'ssn'
     */
    @Test
    public void ssnTest() {
        // TODO: test ssn
    }

    /**
     * Test the property 'dob'
     */
    @Test
    public void dobTest() {
        // TODO: test dob
    }

}
