/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.CustomerAccountMultipleStatement;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CustomerAccountMultipleStatements
 */
public class CustomerAccountMultipleStatementsTest {
    private final CustomerAccountMultipleStatements model = new CustomerAccountMultipleStatements();

    /**
     * Model tests for CustomerAccountMultipleStatements
     */
    @Test
    public void testCustomerAccountMultipleStatements() {
        // TODO: test CustomerAccountMultipleStatements
    }

    /**
     * Test the property 'statements'
     */
    @Test
    public void statementsTest() {
        // TODO: test statements
    }

}
