/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CustomerAuthorizationDetails
 */
public class CustomerAuthorizationDetailsTest {
    private final CustomerAuthorizationDetails model = new CustomerAuthorizationDetails();

    /**
     * Model tests for CustomerAuthorizationDetails
     */
    @Test
    public void testCustomerAuthorizationDetails() {
        // TODO: test CustomerAuthorizationDetails
    }

    /**
     * Test the property 'institutionLoginId'
     */
    @Test
    public void institutionLoginIdTest() {
        // TODO: test institutionLoginId
    }

    /**
     * Test the property 'authorizationStartDate'
     */
    @Test
    public void authorizationStartDateTest() {
        // TODO: test authorizationStartDate
    }

    /**
     * Test the property 'authorizationEndDate'
     */
    @Test
    public void authorizationEndDateTest() {
        // TODO: test authorizationEndDate
    }

}
