/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CustomerAccountSimple
 */
public class CustomerAccountSimpleTest {
    private final CustomerAccountSimple model = new CustomerAccountSimple();

    /**
     * Model tests for CustomerAccountSimple
     */
    @Test
    public void testCustomerAccountSimple() {
        // TODO: test CustomerAccountSimple
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'accountNumberDisplay'
     */
    @Test
    public void accountNumberDisplayTest() {
        // TODO: test accountNumberDisplay
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'aggregationStatusCode'
     */
    @Test
    public void aggregationStatusCodeTest() {
        // TODO: test aggregationStatusCode
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'customerId'
     */
    @Test
    public void customerIdTest() {
        // TODO: test customerId
    }

    /**
     * Test the property 'institutionId'
     */
    @Test
    public void institutionIdTest() {
        // TODO: test institutionId
    }

    /**
     * Test the property 'aggregationSuccessDate'
     */
    @Test
    public void aggregationSuccessDateTest() {
        // TODO: test aggregationSuccessDate
    }

    /**
     * Test the property 'aggregationAttemptDate'
     */
    @Test
    public void aggregationAttemptDateTest() {
        // TODO: test aggregationAttemptDate
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    public void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'institutionLoginId'
     */
    @Test
    public void institutionLoginIdTest() {
        // TODO: test institutionLoginId
    }

    /**
     * Test the property 'displayPosition'
     */
    @Test
    public void displayPositionTest() {
        // TODO: test displayPosition
    }

    /**
     * Test the property 'parentAccount'
     */
    @Test
    public void parentAccountTest() {
        // TODO: test parentAccount
    }

    /**
     * Test the property 'linkedAccountDate'
     */
    @Test
    public void linkedAccountDateTest() {
        // TODO: test linkedAccountDate
    }

}
