/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DepositSwitchDetailsDistributionsInner
 */
public class DepositSwitchDetailsDistributionsInnerTest {
    private final DepositSwitchDetailsDistributionsInner model = new DepositSwitchDetailsDistributionsInner();

    /**
     * Model tests for DepositSwitchDetailsDistributionsInner
     */
    @Test
    public void testDepositSwitchDetailsDistributionsInner() {
        // TODO: test DepositSwitchDetailsDistributionsInner
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'allocatedValue'
     */
    @Test
    public void allocatedValueTest() {
        // TODO: test allocatedValue
    }

    /**
     * Test the property 'bankIdentifier'
     */
    @Test
    public void bankIdentifierTest() {
        // TODO: test bankIdentifier
    }

    /**
     * Test the property 'accountNumberEndsWith'
     */
    @Test
    public void accountNumberEndsWithTest() {
        // TODO: test accountNumberEndsWith
    }

}
