/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DeviceRiskHistoryEvent
 */
public class DeviceRiskHistoryEventTest {
    private final DeviceRiskHistoryEvent model = new DeviceRiskHistoryEvent();

    /**
     * Model tests for DeviceRiskHistoryEvent
     */
    @Test
    public void testDeviceRiskHistoryEvent() {
        // TODO: test DeviceRiskHistoryEvent
    }

    /**
     * Test the property 'riskEvent'
     */
    @Test
    public void riskEventTest() {
        // TODO: test riskEvent
    }

    /**
     * Test the property 'riskEventCount'
     */
    @Test
    public void riskEventCountTest() {
        // TODO: test riskEventCount
    }

    /**
     * Test the property 'riskLevel'
     */
    @Test
    public void riskLevelTest() {
        // TODO: test riskLevel
    }

    /**
     * Test the property 'lastEventDate'
     */
    @Test
    public void lastEventDateTest() {
        // TODO: test lastEventDate
    }

    /**
     * Test the property 'riskSignals'
     */
    @Test
    public void riskSignalsTest() {
        // TODO: test riskSignals
    }

}
