/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Deductions;
import org.openapitools.client.model.Earnings;
import org.openapitools.client.model.MainPayStatementFields;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DirectPayStatements
 */
public class DirectPayStatementsTest {
    private final DirectPayStatements model = new DirectPayStatements();

    /**
     * Model tests for DirectPayStatements
     */
    @Test
    public void testDirectPayStatements() {
        // TODO: test DirectPayStatements
    }

    /**
     * Test the property 'payrollPayHistoryId'
     */
    @Test
    public void payrollPayHistoryIdTest() {
        // TODO: test payrollPayHistoryId
    }

    /**
     * Test the property 'lastPayPeriodIndicator'
     */
    @Test
    public void lastPayPeriodIndicatorTest() {
        // TODO: test lastPayPeriodIndicator
    }

    /**
     * Test the property 'mainPayStatementFields'
     */
    @Test
    public void mainPayStatementFieldsTest() {
        // TODO: test mainPayStatementFields
    }

    /**
     * Test the property 'earnings'
     */
    @Test
    public void earningsTest() {
        // TODO: test earnings
    }

    /**
     * Test the property 'deductions'
     */
    @Test
    public void deductionsTest() {
        // TODO: test deductions
    }

}
