/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.DESAddress;
import org.openapitools.client.model.EntitiesInner;
import org.openapitools.client.model.InputMerchantInformation;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EnrichedTransaction
 */
public class EnrichedTransactionTest {
    private final EnrichedTransaction model = new EnrichedTransaction();

    /**
     * Model tests for EnrichedTransaction
     */
    @Test
    public void testEnrichedTransaction() {
        // TODO: test EnrichedTransaction
    }

    /**
     * Test the property 'externalCustomerId'
     */
    @Test
    public void externalCustomerIdTest() {
        // TODO: test externalCustomerId
    }

    /**
     * Test the property 'externalAccountId'
     */
    @Test
    public void externalAccountIdTest() {
        // TODO: test externalAccountId
    }

    /**
     * Test the property 'accountType'
     */
    @Test
    public void accountTypeTest() {
        // TODO: test accountType
    }

    /**
     * Test the property 'externalTransactionId'
     */
    @Test
    public void externalTransactionIdTest() {
        // TODO: test externalTransactionId
    }

    /**
     * Test the property 'postedTimestamp'
     */
    @Test
    public void postedTimestampTest() {
        // TODO: test postedTimestamp
    }

    /**
     * Test the property 'transactionTimestamp'
     */
    @Test
    public void transactionTimestampTest() {
        // TODO: test transactionTimestamp
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'memo'
     */
    @Test
    public void memoTest() {
        // TODO: test memo
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'transactionFee'
     */
    @Test
    public void transactionFeeTest() {
        // TODO: test transactionFee
    }

    /**
     * Test the property 'transactionCategory'
     */
    @Test
    public void transactionCategoryTest() {
        // TODO: test transactionCategory
    }

    /**
     * Test the property 'transactionCategoryScore'
     */
    @Test
    public void transactionCategoryScoreTest() {
        // TODO: test transactionCategoryScore
    }

    /**
     * Test the property 'transactionCategoryGroup'
     */
    @Test
    public void transactionCategoryGroupTest() {
        // TODO: test transactionCategoryGroup
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'directionIndicator'
     */
    @Test
    public void directionIndicatorTest() {
        // TODO: test directionIndicator
    }

    /**
     * Test the property 'entities'
     */
    @Test
    public void entitiesTest() {
        // TODO: test entities
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'additionalDetails'
     */
    @Test
    public void additionalDetailsTest() {
        // TODO: test additionalDetails
    }

    /**
     * Test the property 'cardAcceptorId'
     */
    @Test
    public void cardAcceptorIdTest() {
        // TODO: test cardAcceptorId
    }

    /**
     * Test the property 'inputIsRecurringTransaction'
     */
    @Test
    public void inputIsRecurringTransactionTest() {
        // TODO: test inputIsRecurringTransaction
    }

    /**
     * Test the property 'inputMerchantInformation'
     */
    @Test
    public void inputMerchantInformationTest() {
        // TODO: test inputMerchantInformation
    }

    /**
     * Test the property 'isRecurringTransaction'
     */
    @Test
    public void isRecurringTransactionTest() {
        // TODO: test isRecurringTransaction
    }

    /**
     * Test the property 'locationId'
     */
    @Test
    public void locationIdTest() {
        // TODO: test locationId
    }

    /**
     * Test the property 'isEcommerce'
     */
    @Test
    public void isEcommerceTest() {
        // TODO: test isEcommerce
    }

    /**
     * Test the property 'isBrickAndMortar'
     */
    @Test
    public void isBrickAndMortarTest() {
        // TODO: test isBrickAndMortar
    }

    /**
     * Test the property 'matchConfidenceScore'
     */
    @Test
    public void matchConfidenceScoreTest() {
        // TODO: test matchConfidenceScore
    }

}
