/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FindTransactionConstraintsInner
 */
public class FindTransactionConstraintsInnerTest {
    private final FindTransactionConstraintsInner model = new FindTransactionConstraintsInner();

    /**
     * Model tests for FindTransactionConstraintsInner
     */
    @Test
    public void testFindTransactionConstraintsInner() {
        // TODO: test FindTransactionConstraintsInner
    }

    /**
     * Test the property 'findTransactionDescriptionMemo'
     */
    @Test
    public void findTransactionDescriptionMemoTest() {
        // TODO: test findTransactionDescriptionMemo
    }

    /**
     * Test the property 'findTransactionAmountFrom'
     */
    @Test
    public void findTransactionAmountFromTest() {
        // TODO: test findTransactionAmountFrom
    }

    /**
     * Test the property 'findTransactionAmountTo'
     */
    @Test
    public void findTransactionAmountToTest() {
        // TODO: test findTransactionAmountTo
    }

    /**
     * Test the property 'findTransactionCategory'
     */
    @Test
    public void findTransactionCategoryTest() {
        // TODO: test findTransactionCategory
    }

}
