/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FixConnectParameters
 */
public class FixConnectParametersTest {
    private final FixConnectParameters model = new FixConnectParameters();

    /**
     * Model tests for FixConnectParameters
     */
    @Test
    public void testFixConnectParameters() {
        // TODO: test FixConnectParameters
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'partnerId'
     */
    @Test
    public void partnerIdTest() {
        // TODO: test partnerId
    }

    /**
     * Test the property 'customerId'
     */
    @Test
    public void customerIdTest() {
        // TODO: test customerId
    }

    /**
     * Test the property 'institutionLoginId'
     */
    @Test
    public void institutionLoginIdTest() {
        // TODO: test institutionLoginId
    }

    /**
     * Test the property 'redirectUri'
     */
    @Test
    public void redirectUriTest() {
        // TODO: test redirectUri
    }

    /**
     * Test the property 'webhook'
     */
    @Test
    public void webhookTest() {
        // TODO: test webhook
    }

    /**
     * Test the property 'webhookContentType'
     */
    @Test
    public void webhookContentTypeTest() {
        // TODO: test webhookContentType
    }

    /**
     * Test the property 'webhookData'
     */
    @Test
    public void webhookDataTest() {
        // TODO: test webhookData
    }

    /**
     * Test the property 'webhookHeaders'
     */
    @Test
    public void webhookHeadersTest() {
        // TODO: test webhookHeaders
    }

    /**
     * Test the property 'experience'
     */
    @Test
    public void experienceTest() {
        // TODO: test experience
    }

    /**
     * Test the property 'singleUseUrl'
     */
    @Test
    public void singleUseUrlTest() {
        // TODO: test singleUseUrl
    }

    /**
     * Test the property 'isHostedInMobileApp'
     */
    @Test
    public void isHostedInMobileAppTest() {
        // TODO: test isHostedInMobileApp
    }

    /**
     * Test the property 'isWebView'
     */
    @Test
    public void isWebViewTest() {
        // TODO: test isWebView
    }

}
