/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ForesightAnalyticsReportData;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ForesightAnalyticsReportConstraints
 */
public class ForesightAnalyticsReportConstraintsTest {
    private final ForesightAnalyticsReportConstraints model = new ForesightAnalyticsReportConstraints();

    /**
     * Model tests for ForesightAnalyticsReportConstraints
     */
    @Test
    public void testForesightAnalyticsReportConstraints() {
        // TODO: test ForesightAnalyticsReportConstraints
    }

    /**
     * Test the property 'analyticsReportData'
     */
    @Test
    public void analyticsReportDataTest() {
        // TODO: test analyticsReportData
    }

    /**
     * Test the property 'accountIds'
     */
    @Test
    public void accountIdsTest() {
        // TODO: test accountIds
    }

    /**
     * Test the property 'fromDate'
     */
    @Test
    public void fromDateTest() {
        // TODO: test fromDate
    }

}
