/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Branding;
import org.openapitools.client.model.InstitutionAddress;
import org.openapitools.client.model.InstitutionsWithRoutingNumberCountryCodesInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InstitutionsWithRoutingNumber
 */
public class InstitutionsWithRoutingNumberTest {
    private final InstitutionsWithRoutingNumber model = new InstitutionsWithRoutingNumber();

    /**
     * Model tests for InstitutionsWithRoutingNumber
     */
    @Test
    public void testInstitutionsWithRoutingNumber() {
        // TODO: test InstitutionsWithRoutingNumber
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'transAgg'
     */
    @Test
    public void transAggTest() {
        // TODO: test transAgg
    }

    /**
     * Test the property 'ach'
     */
    @Test
    public void achTest() {
        // TODO: test ach
    }

    /**
     * Test the property 'stateAgg'
     */
    @Test
    public void stateAggTest() {
        // TODO: test stateAgg
    }

    /**
     * Test the property 'voi'
     */
    @Test
    public void voiTest() {
        // TODO: test voi
    }

    /**
     * Test the property 'voa'
     */
    @Test
    public void voaTest() {
        // TODO: test voa
    }

    /**
     * Test the property 'aha'
     */
    @Test
    public void ahaTest() {
        // TODO: test aha
    }

    /**
     * Test the property 'availBalance'
     */
    @Test
    public void availBalanceTest() {
        // TODO: test availBalance
    }

    /**
     * Test the property 'accountOwner'
     */
    @Test
    public void accountOwnerTest() {
        // TODO: test accountOwner
    }

    /**
     * Test the property 'studentLoanData'
     */
    @Test
    public void studentLoanDataTest() {
        // TODO: test studentLoanData
    }

    /**
     * Test the property 'loanPaymentDetails'
     */
    @Test
    public void loanPaymentDetailsTest() {
        // TODO: test loanPaymentDetails
    }

    /**
     * Test the property 'paymentInitiation'
     */
    @Test
    public void paymentInitiationTest() {
        // TODO: test paymentInitiation
    }

    /**
     * Test the property 'billPayData'
     */
    @Test
    public void billPayDataTest() {
        // TODO: test billPayData
    }

    /**
     * Test the property 'liabilityData'
     */
    @Test
    public void liabilityDataTest() {
        // TODO: test liabilityData
    }

    /**
     * Test the property 'accountTypeDescription'
     */
    @Test
    public void accountTypeDescriptionTest() {
        // TODO: test accountTypeDescription
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'urlHomeApp'
     */
    @Test
    public void urlHomeAppTest() {
        // TODO: test urlHomeApp
    }

    /**
     * Test the property 'urlLogonApp'
     */
    @Test
    public void urlLogonAppTest() {
        // TODO: test urlLogonApp
    }

    /**
     * Test the property 'oauthEnabled'
     */
    @Test
    public void oauthEnabledTest() {
        // TODO: test oauthEnabled
    }

    /**
     * Test the property 'urlForgotPassword'
     */
    @Test
    public void urlForgotPasswordTest() {
        // TODO: test urlForgotPassword
    }

    /**
     * Test the property 'urlOnlineRegistration'
     */
    @Test
    public void urlOnlineRegistrationTest() {
        // TODO: test urlOnlineRegistration
    }

    /**
     * Test the property 'propertyClass'
     */
    @Test
    public void propertyClassTest() {
        // TODO: test propertyClass
    }

    /**
     * Test the property 'specialText'
     */
    @Test
    public void specialTextTest() {
        // TODO: test specialText
    }

    /**
     * Test the property 'timeZone'
     */
    @Test
    public void timeZoneTest() {
        // TODO: test timeZone
    }

    /**
     * Test the property 'specialInstructions'
     */
    @Test
    public void specialInstructionsTest() {
        // TODO: test specialInstructions
    }

    /**
     * Test the property 'specialInstutionsTitle'
     */
    @Test
    public void specialInstutionsTitleTest() {
        // TODO: test specialInstutionsTitle
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'newInstitutionId'
     */
    @Test
    public void newInstitutionIdTest() {
        // TODO: test newInstitutionId
    }

    /**
     * Test the property 'branding'
     */
    @Test
    public void brandingTest() {
        // TODO: test branding
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'oauthInstitutionId'
     */
    @Test
    public void oauthInstitutionIdTest() {
        // TODO: test oauthInstitutionId
    }

    /**
     * Test the property 'countryCodes'
     */
    @Test
    public void countryCodesTest() {
        // TODO: test countryCodes
    }

    /**
     * Test the property 'overallStatusTemp'
     */
    @Test
    public void overallStatusTempTest() {
        // TODO: test overallStatusTemp
    }

    /**
     * Test the property 'transAggStatus'
     */
    @Test
    public void transAggStatusTest() {
        // TODO: test transAggStatus
    }

    /**
     * Test the property 'voaStatus'
     */
    @Test
    public void voaStatusTest() {
        // TODO: test voaStatus
    }

    /**
     * Test the property 'voiStatus'
     */
    @Test
    public void voiStatusTest() {
        // TODO: test voiStatus
    }

    /**
     * Test the property 'stateAggStatus'
     */
    @Test
    public void stateAggStatusTest() {
        // TODO: test stateAggStatus
    }

    /**
     * Test the property 'achStatus'
     */
    @Test
    public void achStatusTest() {
        // TODO: test achStatus
    }

    /**
     * Test the property 'ahaStatus'
     */
    @Test
    public void ahaStatusTest() {
        // TODO: test ahaStatus
    }

}
