/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.FinancialInstitution;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InstitutionResponse
 */
public class InstitutionResponseTest {
    private final InstitutionResponse model = new InstitutionResponse();

    /**
     * Model tests for InstitutionResponse
     */
    @Test
    public void testInstitutionResponse() {
        // TODO: test InstitutionResponse
    }

    /**
     * Test the property 'found'
     */
    @Test
    public void foundTest() {
        // TODO: test found
    }

    /**
     * Test the property 'displaying'
     */
    @Test
    public void displayingTest() {
        // TODO: test displaying
    }

    /**
     * Test the property 'moreAvailable'
     */
    @Test
    public void moreAvailableTest() {
        // TODO: test moreAvailable
    }

    /**
     * Test the property 'institutions'
     */
    @Test
    public void institutionsTest() {
        // TODO: test institutions
    }

}
