/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.LoanPaymentDetailsLoan;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for LoanPaymentDetailsGroup
 */
public class LoanPaymentDetailsGroupTest {
    private final LoanPaymentDetailsGroup model = new LoanPaymentDetailsGroup();

    /**
     * Model tests for LoanPaymentDetailsGroup
     */
    @Test
    public void testLoanPaymentDetailsGroup() {
        // TODO: test LoanPaymentDetailsGroup
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'groupNumber'
     */
    @Test
    public void groupNumberTest() {
        // TODO: test groupNumber
    }

    /**
     * Test the property 'groupPaymentNumber'
     */
    @Test
    public void groupPaymentNumberTest() {
        // TODO: test groupPaymentNumber
    }

    /**
     * Test the property 'groupPaymentAddress'
     */
    @Test
    public void groupPaymentAddressTest() {
        // TODO: test groupPaymentAddress
    }

    /**
     * Test the property 'groupFuturePayoffAmount'
     */
    @Test
    public void groupFuturePayoffAmountTest() {
        // TODO: test groupFuturePayoffAmount
    }

    /**
     * Test the property 'groupFuturePayoffDate'
     */
    @Test
    public void groupFuturePayoffDateTest() {
        // TODO: test groupFuturePayoffDate
    }

    /**
     * Test the property 'groupLoanDetail'
     */
    @Test
    public void groupLoanDetailTest() {
        // TODO: test groupLoanDetail
    }

}
