/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for LoanPaymentDetailsLoan
 */
public class LoanPaymentDetailsLoanTest {
    private final LoanPaymentDetailsLoan model = new LoanPaymentDetailsLoan();

    /**
     * Model tests for LoanPaymentDetailsLoan
     */
    @Test
    public void testLoanPaymentDetailsLoan() {
        // TODO: test LoanPaymentDetailsLoan
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'loanNumber'
     */
    @Test
    public void loanNumberTest() {
        // TODO: test loanNumber
    }

    /**
     * Test the property 'loanPaymentNumber'
     */
    @Test
    public void loanPaymentNumberTest() {
        // TODO: test loanPaymentNumber
    }

    /**
     * Test the property 'loanPaymentAddress'
     */
    @Test
    public void loanPaymentAddressTest() {
        // TODO: test loanPaymentAddress
    }

    /**
     * Test the property 'loanFuturePayoffAmount'
     */
    @Test
    public void loanFuturePayoffAmountTest() {
        // TODO: test loanFuturePayoffAmount
    }

    /**
     * Test the property 'loanFuturePayoffDate'
     */
    @Test
    public void loanFuturePayoffDateTest() {
        // TODO: test loanFuturePayoffDate
    }

}
