/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MicroDepositDetails
 */
public class MicroDepositDetailsTest {
    private final MicroDepositDetails model = new MicroDepositDetails();

    /**
     * Model tests for MicroDepositDetails
     */
    @Test
    public void testMicroDepositDetails() {
        // TODO: test MicroDepositDetails
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'statusDescription'
     */
    @Test
    public void statusDescriptionTest() {
        // TODO: test statusDescription
    }

    /**
     * Test the property 'creationDate'
     */
    @Test
    public void creationDateTest() {
        // TODO: test creationDate
    }

    /**
     * Test the property 'routingNumber'
     */
    @Test
    public void routingNumberTest() {
        // TODO: test routingNumber
    }

    /**
     * Test the property 'accountNumberLast4'
     */
    @Test
    public void accountNumberLast4Test() {
        // TODO: test accountNumberLast4
    }

    /**
     * Test the property 'autoVerifiedAccount'
     */
    @Test
    public void autoVerifiedAccountTest() {
        // TODO: test autoVerifiedAccount
    }

    /**
     * Test the property 'railType'
     */
    @Test
    public void railTypeTest() {
        // TODO: test railType
    }

}
