/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Arrays;
import org.openapitools.client.model.NsfReasonItem;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for NsfIndicator
 */
public class NsfIndicatorTest {
    private final NsfIndicator model = new NsfIndicator();

    /**
     * Model tests for NsfIndicator
     */
    @Test
    public void testNsfIndicator() {
        // TODO: test NsfIndicator
    }

    /**
     * Test the property 'potentialSettlementDate'
     */
    @Test
    public void potentialSettlementDateTest() {
        // TODO: test potentialSettlementDate
    }

    /**
     * Test the property 'score'
     */
    @Test
    public void scoreTest() {
        // TODO: test score
    }

    /**
     * Test the property 'indicator'
     */
    @Test
    public void indicatorTest() {
        // TODO: test indicator
    }

    /**
     * Test the property 'reasons'
     */
    @Test
    public void reasonsTest() {
        // TODO: test reasons
    }

}
