/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for NsfReasonItem
 */
public class NsfReasonItemTest {
    private final NsfReasonItem model = new NsfReasonItem();

    /**
     * Model tests for NsfReasonItem
     */
    @Test
    public void testNsfReasonItem() {
        // TODO: test NsfReasonItem
    }

    /**
     * Test the property 'recentBalance'
     */
    @Test
    public void recentBalanceTest() {
        // TODO: test recentBalance
    }

    /**
     * Test the property 'balanceHistory'
     */
    @Test
    public void balanceHistoryTest() {
        // TODO: test balanceHistory
    }

    /**
     * Test the property 'nsfHistory'
     */
    @Test
    public void nsfHistoryTest() {
        // TODO: test nsfHistory
    }

    /**
     * Test the property 'recentNsfHistory'
     */
    @Test
    public void recentNsfHistoryTest() {
        // TODO: test recentNsfHistory
    }

    /**
     * Test the property 'recurringNsf'
     */
    @Test
    public void recurringNsfTest() {
        // TODO: test recurringNsf
    }

    /**
     * Test the property 'spendHistory'
     */
    @Test
    public void spendHistoryTest() {
        // TODO: test spendHistory
    }

    /**
     * Test the property 'depositHistory'
     */
    @Test
    public void depositHistoryTest() {
        // TODO: test depositHistory
    }

    /**
     * Test the property 'transactionAmount'
     */
    @Test
    public void transactionAmountTest() {
        // TODO: test transactionAmount
    }

}
