/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.client.model.ObbAccountOwner;
import org.openapitools.client.model.ObbInstitution;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ObbAccountDetails
 */
public class ObbAccountDetailsTest {
    private final ObbAccountDetails model = new ObbAccountDetails();

    /**
     * Model tests for ObbAccountDetails
     */
    @Test
    public void testObbAccountDetails() {
        // TODO: test ObbAccountDetails
    }

    /**
     * Test the property 'accountNumberDisplay'
     */
    @Test
    public void accountNumberDisplayTest() {
        // TODO: test accountNumberDisplay
    }

    /**
     * Test the property 'accountOwner'
     */
    @Test
    public void accountOwnerTest() {
        // TODO: test accountOwner
    }

    /**
     * Test the property 'aggregationAttemptDate'
     */
    @Test
    public void aggregationAttemptDateTest() {
        // TODO: test aggregationAttemptDate
    }

    /**
     * Test the property 'aggregationStatusCode'
     */
    @Test
    public void aggregationStatusCodeTest() {
        // TODO: test aggregationStatusCode
    }

    /**
     * Test the property 'aggregationSuccessDate'
     */
    @Test
    public void aggregationSuccessDateTest() {
        // TODO: test aggregationSuccessDate
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'currentBalance'
     */
    @Test
    public void currentBalanceTest() {
        // TODO: test currentBalance
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'institution'
     */
    @Test
    public void institutionTest() {
        // TODO: test institution
    }

    /**
     * Test the property 'institutionLoginId'
     */
    @Test
    public void institutionLoginIdTest() {
        // TODO: test institutionLoginId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'realAccountNumberLast4'
     */
    @Test
    public void realAccountNumberLast4Test() {
        // TODO: test realAccountNumberLast4
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
