/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ObbCurrentReportRequestDetails
 */
public class ObbCurrentReportRequestDetailsTest {
    private final ObbCurrentReportRequestDetails model = new ObbCurrentReportRequestDetails();

    /**
     * Model tests for ObbCurrentReportRequestDetails
     */
    @Test
    public void testObbCurrentReportRequestDetails() {
        // TODO: test ObbCurrentReportRequestDetails
    }

    /**
     * Test the property 'reportBeginDate'
     */
    @Test
    public void reportBeginDateTest() {
        // TODO: test reportBeginDate
    }

    /**
     * Test the property 'reportEndDate'
     */
    @Test
    public void reportEndDateTest() {
        // TODO: test reportEndDate
    }

    /**
     * Test the property 'reportRequestDate'
     */
    @Test
    public void reportRequestDateTest() {
        // TODO: test reportRequestDate
    }

    /**
     * Test the property 'requestedDaysForReport'
     */
    @Test
    public void requestedDaysForReportTest() {
        // TODO: test requestedDaysForReport
    }

    /**
     * Test the property 'requestedReportBeginDate'
     */
    @Test
    public void requestedReportBeginDateTest() {
        // TODO: test requestedReportBeginDate
    }

}
