/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ObbDataAvailability
 */
public class ObbDataAvailabilityTest {
    private final ObbDataAvailability model = new ObbDataAvailability();

    /**
     * Model tests for ObbDataAvailability
     */
    @Test
    public void testObbDataAvailability() {
        // TODO: test ObbDataAvailability
    }

    /**
     * Test the property 'historicAvailabilityBeginDate'
     */
    @Test
    public void historicAvailabilityBeginDateTest() {
        // TODO: test historicAvailabilityBeginDate
    }

    /**
     * Test the property 'historicAvailabilityEndDate'
     */
    @Test
    public void historicAvailabilityEndDateTest() {
        // TODO: test historicAvailabilityEndDate
    }

    /**
     * Test the property 'historicAvailableDays'
     */
    @Test
    public void historicAvailableDaysTest() {
        // TODO: test historicAvailableDays
    }

    /**
     * Test the property 'historicDataAvailability'
     */
    @Test
    public void historicDataAvailabilityTest() {
        // TODO: test historicDataAvailability
    }

}
