/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ObbDateRangeAndAmount
 */
public class ObbDateRangeAndAmountTest {
    private final ObbDateRangeAndAmount model = new ObbDateRangeAndAmount();

    /**
     * Model tests for ObbDateRangeAndAmount
     */
    @Test
    public void testObbDateRangeAndAmount() {
        // TODO: test ObbDateRangeAndAmount
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'period'
     */
    @Test
    public void periodTest() {
        // TODO: test period
    }

    /**
     * Test the property 'periodBeginDate'
     */
    @Test
    public void periodBeginDateTest() {
        // TODO: test periodBeginDate
    }

    /**
     * Test the property 'periodEndDate'
     */
    @Test
    public void periodEndDateTest() {
        // TODO: test periodEndDate
    }

}
