/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ObbReportHeader
 */
public class ObbReportHeaderTest {
    private final ObbReportHeader model = new ObbReportHeader();

    /**
     * Model tests for ObbReportHeader
     */
    @Test
    public void testObbReportHeader() {
        // TODO: test ObbReportHeader
    }

    /**
     * Test the property 'businessAddress'
     */
    @Test
    public void businessAddressTest() {
        // TODO: test businessAddress
    }

    /**
     * Test the property 'businessCity'
     */
    @Test
    public void businessCityTest() {
        // TODO: test businessCity
    }

    /**
     * Test the property 'businessName'
     */
    @Test
    public void businessNameTest() {
        // TODO: test businessName
    }

    /**
     * Test the property 'businessState'
     */
    @Test
    public void businessStateTest() {
        // TODO: test businessState
    }

    /**
     * Test the property 'businessZip'
     */
    @Test
    public void businessZipTest() {
        // TODO: test businessZip
    }

    /**
     * Test the property 'referenceNumber'
     */
    @Test
    public void referenceNumberTest() {
        // TODO: test referenceNumber
    }

    /**
     * Test the property 'reportDate'
     */
    @Test
    public void reportDateTest() {
        // TODO: test reportDate
    }

    /**
     * Test the property 'reportId'
     */
    @Test
    public void reportIdTest() {
        // TODO: test reportId
    }

}
