/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PartnerCredentialsWithNewSecret
 */
public class PartnerCredentialsWithNewSecretTest {
    private final PartnerCredentialsWithNewSecret model = new PartnerCredentialsWithNewSecret();

    /**
     * Model tests for PartnerCredentialsWithNewSecret
     */
    @Test
    public void testPartnerCredentialsWithNewSecret() {
        // TODO: test PartnerCredentialsWithNewSecret
    }

    /**
     * Test the property 'partnerId'
     */
    @Test
    public void partnerIdTest() {
        // TODO: test partnerId
    }

    /**
     * Test the property 'partnerSecret'
     */
    @Test
    public void partnerSecretTest() {
        // TODO: test partnerSecret
    }

    /**
     * Test the property 'newPartnerSecret'
     */
    @Test
    public void newPartnerSecretTest() {
        // TODO: test newPartnerSecret
    }

    /**
     * Test the property 'immediate'
     */
    @Test
    public void immediateTest() {
        // TODO: test immediate
    }

}
