/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.PEBAccountDetails;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaymentEnablementBundle
 */
public class PaymentEnablementBundleTest {
    private final PaymentEnablementBundle model = new PaymentEnablementBundle();

    /**
     * Model tests for PaymentEnablementBundle
     */
    @Test
    public void testPaymentEnablementBundle() {
        // TODO: test PaymentEnablementBundle
    }

    /**
     * Test the property 'customerId'
     */
    @Test
    public void customerIdTest() {
        // TODO: test customerId
    }

    /**
     * Test the property 'errorCount'
     */
    @Test
    public void errorCountTest() {
        // TODO: test errorCount
    }

    /**
     * Test the property 'accountCount'
     */
    @Test
    public void accountCountTest() {
        // TODO: test accountCount
    }

    /**
     * Test the property 'accountIdentitySuccessCount'
     */
    @Test
    public void accountIdentitySuccessCountTest() {
        // TODO: test accountIdentitySuccessCount
    }

    /**
     * Test the property 'balanceDetailsSuccessCount'
     */
    @Test
    public void balanceDetailsSuccessCountTest() {
        // TODO: test balanceDetailsSuccessCount
    }

    /**
     * Test the property 'paymentInstructionSuccessCount'
     */
    @Test
    public void paymentInstructionSuccessCountTest() {
        // TODO: test paymentInstructionSuccessCount
    }

    /**
     * Test the property 'accounts'
     */
    @Test
    public void accountsTest() {
        // TODO: test accounts
    }

}
