/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Arrays;
import org.openapitools.client.model.NsfReturnRisk;
import org.openapitools.client.model.PaymentSuccessIndicatorsTransaction;
import org.openapitools.client.model.UnauthorizedReturnRisk;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaymentSuccessIndicators
 */
public class PaymentSuccessIndicatorsTest {
    private final PaymentSuccessIndicators model = new PaymentSuccessIndicators();

    /**
     * Model tests for PaymentSuccessIndicators
     */
    @Test
    public void testPaymentSuccessIndicators() {
        // TODO: test PaymentSuccessIndicators
    }

    /**
     * Test the property 'payRequestId'
     */
    @Test
    public void payRequestIdTest() {
        // TODO: test payRequestId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'customerId'
     */
    @Test
    public void customerIdTest() {
        // TODO: test customerId
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'requestDate'
     */
    @Test
    public void requestDateTest() {
        // TODO: test requestDate
    }

    /**
     * Test the property 'transaction'
     */
    @Test
    public void transactionTest() {
        // TODO: test transaction
    }

    /**
     * Test the property 'nsfReturnRisk'
     */
    @Test
    public void nsfReturnRiskTest() {
        // TODO: test nsfReturnRisk
    }

    /**
     * Test the property 'unauthorizedReturnRisk'
     */
    @Test
    public void unauthorizedReturnRiskTest() {
        // TODO: test unauthorizedReturnRisk
    }

}
