/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaymentSuccessIndicatorsAddress
 */
public class PaymentSuccessIndicatorsAddressTest {
    private final PaymentSuccessIndicatorsAddress model = new PaymentSuccessIndicatorsAddress();

    /**
     * Model tests for PaymentSuccessIndicatorsAddress
     */
    @Test
    public void testPaymentSuccessIndicatorsAddress() {
        // TODO: test PaymentSuccessIndicatorsAddress
    }

    /**
     * Test the property 'streetLine1'
     */
    @Test
    public void streetLine1Test() {
        // TODO: test streetLine1
    }

    /**
     * Test the property 'streetLine2'
     */
    @Test
    public void streetLine2Test() {
        // TODO: test streetLine2
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'postalCode'
     */
    @Test
    public void postalCodeTest() {
        // TODO: test postalCode
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

}
