/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Indicator;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaymentSuccessIndicator
 */
public class PaymentSuccessIndicatorTest {
    private final PaymentSuccessIndicator model = new PaymentSuccessIndicator();

    /**
     * Model tests for PaymentSuccessIndicator
     */
    @Test
    public void testPaymentSuccessIndicator() {
        // TODO: test PaymentSuccessIndicator
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'customerId'
     */
    @Test
    public void customerIdTest() {
        // TODO: test customerId
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'payReqId'
     */
    @Test
    public void payReqIdTest() {
        // TODO: test payReqId
    }

    /**
     * Test the property 'settleByDate'
     */
    @Test
    public void settleByDateTest() {
        // TODO: test settleByDate
    }

    /**
     * Test the property 'settlementAmount'
     */
    @Test
    public void settlementAmountTest() {
        // TODO: test settlementAmount
    }

    /**
     * Test the property 'availableBalance'
     */
    @Test
    public void availableBalanceTest() {
        // TODO: test availableBalance
    }

    /**
     * Test the property 'indicatorsByDay'
     */
    @Test
    public void indicatorsByDayTest() {
        // TODO: test indicatorsByDay
    }

}
