/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.PaymentSuccessIndicatorsTransaction;
import org.openapitools.client.model.PaymentSuccessIndicatorsUser;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaymentSuccessIndicatorsProperties
 */
public class PaymentSuccessIndicatorsPropertiesTest {
    private final PaymentSuccessIndicatorsProperties model = new PaymentSuccessIndicatorsProperties();

    /**
     * Model tests for PaymentSuccessIndicatorsProperties
     */
    @Test
    public void testPaymentSuccessIndicatorsProperties() {
        // TODO: test PaymentSuccessIndicatorsProperties
    }

    /**
     * Test the property 'transaction'
     */
    @Test
    public void transactionTest() {
        // TODO: test transaction
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

}
