/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PayrollDataOut
 */
public class PayrollDataOutTest {
    private final PayrollDataOut model = new PayrollDataOut();

    /**
     * Model tests for PayrollDataOut
     */
    @Test
    public void testPayrollDataOut() {
        // TODO: test PayrollDataOut
    }

    /**
     * Test the property 'payrollDataRetrievalId'
     */
    @Test
    public void payrollDataRetrievalIdTest() {
        // TODO: test payrollDataRetrievalId
    }

    /**
     * Test the property 'payrollAggregatorResponseId'
     */
    @Test
    public void payrollAggregatorResponseIdTest() {
        // TODO: test payrollAggregatorResponseId
    }

    /**
     * Test the property 'consentMethod'
     */
    @Test
    public void consentMethodTest() {
        // TODO: test consentMethod
    }

    /**
     * Test the property 'employmentIds'
     */
    @Test
    public void employmentIdsTest() {
        // TODO: test employmentIds
    }

    /**
     * Test the property 'payrollAccountIds'
     */
    @Test
    public void payrollAccountIdsTest() {
        // TODO: test payrollAccountIds
    }

    /**
     * Test the property 'reportId'
     */
    @Test
    public void reportIdTest() {
        // TODO: test reportId
    }

}
