/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.PayrollEmployeeRecord;
import org.openapitools.client.model.PayrollEmploymentRecord;
import org.openapitools.client.model.PayrollVOEIncomeRecord;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PayrollEmploymentHistoryVOE
 */
public class PayrollEmploymentHistoryVOETest {
    private final PayrollEmploymentHistoryVOE model = new PayrollEmploymentHistoryVOE();

    /**
     * Model tests for PayrollEmploymentHistoryVOE
     */
    @Test
    public void testPayrollEmploymentHistoryVOE() {
        // TODO: test PayrollEmploymentHistoryVOE
    }

    /**
     * Test the property 'asOfDate'
     */
    @Test
    public void asOfDateTest() {
        // TODO: test asOfDate
    }

    /**
     * Test the property 'employerName'
     */
    @Test
    public void employerNameTest() {
        // TODO: test employerName
    }

    /**
     * Test the property 'payrollSource'
     */
    @Test
    public void payrollSourceTest() {
        // TODO: test payrollSource
    }

    /**
     * Test the property 'payrollProvider'
     */
    @Test
    public void payrollProviderTest() {
        // TODO: test payrollProvider
    }

    /**
     * Test the property 'employee'
     */
    @Test
    public void employeeTest() {
        // TODO: test employee
    }

    /**
     * Test the property 'employment'
     */
    @Test
    public void employmentTest() {
        // TODO: test employment
    }

    /**
     * Test the property 'income'
     */
    @Test
    public void incomeTest() {
        // TODO: test income
    }

}
