/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AnnualIncome;
import org.openapitools.client.model.DirectPayStatements;
import org.openapitools.client.model.MonthlyIncome;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PayrollVOIEIncomeRecord
 */
public class PayrollVOIEIncomeRecordTest {
    private final PayrollVOIEIncomeRecord model = new PayrollVOIEIncomeRecord();

    /**
     * Model tests for PayrollVOIEIncomeRecord
     */
    @Test
    public void testPayrollVOIEIncomeRecord() {
        // TODO: test PayrollVOIEIncomeRecord
    }

    /**
     * Test the property 'payFrequency'
     */
    @Test
    public void payFrequencyTest() {
        // TODO: test payFrequency
    }

    /**
     * Test the property 'payType'
     */
    @Test
    public void payTypeTest() {
        // TODO: test payType
    }

    /**
     * Test the property 'basePayRate'
     */
    @Test
    public void basePayRateTest() {
        // TODO: test basePayRate
    }

    /**
     * Test the property 'basePayRateUnit'
     */
    @Test
    public void basePayRateUnitTest() {
        // TODO: test basePayRateUnit
    }

    /**
     * Test the property 'oldestPayStatementAvailable'
     */
    @Test
    public void oldestPayStatementAvailableTest() {
        // TODO: test oldestPayStatementAvailable
    }

    /**
     * Test the property 'annualIncome'
     */
    @Test
    public void annualIncomeTest() {
        // TODO: test annualIncome
    }

    /**
     * Test the property 'monthlyIncome'
     */
    @Test
    public void monthlyIncomeTest() {
        // TODO: test monthlyIncome
    }

    /**
     * Test the property 'directPayStatements'
     */
    @Test
    public void directPayStatementsTest() {
        // TODO: test directPayStatements
    }

}
