/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaystubTxVerifyMonthlyIncomeRecord
 */
public class PaystubTxVerifyMonthlyIncomeRecordTest {
    private final PaystubTxVerifyMonthlyIncomeRecord model = new PaystubTxVerifyMonthlyIncomeRecord();

    /**
     * Model tests for PaystubTxVerifyMonthlyIncomeRecord
     */
    @Test
    public void testPaystubTxVerifyMonthlyIncomeRecord() {
        // TODO: test PaystubTxVerifyMonthlyIncomeRecord
    }

    /**
     * Test the property 'estimatedMonthlyBasePay'
     */
    @Test
    public void estimatedMonthlyBasePayTest() {
        // TODO: test estimatedMonthlyBasePay
    }

    /**
     * Test the property 'estimatedMonthlyOvertimePay'
     */
    @Test
    public void estimatedMonthlyOvertimePayTest() {
        // TODO: test estimatedMonthlyOvertimePay
    }

    /**
     * Test the property 'estimatedMonthlyBonusPay'
     */
    @Test
    public void estimatedMonthlyBonusPayTest() {
        // TODO: test estimatedMonthlyBonusPay
    }

    /**
     * Test the property 'estimatedMonthlyCommissionPay'
     */
    @Test
    public void estimatedMonthlyCommissionPayTest() {
        // TODO: test estimatedMonthlyCommissionPay
    }

    /**
     * Test the property 'estimatedMonthlyOtherPay'
     */
    @Test
    public void estimatedMonthlyOtherPayTest() {
        // TODO: test estimatedMonthlyOtherPay
    }

    /**
     * Test the property 'estimatedMonthlyTotalPay'
     */
    @Test
    public void estimatedMonthlyTotalPayTest() {
        // TODO: test estimatedMonthlyTotalPay
    }

}
