/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaySwitchDetailsPaymentMethodsInner
 */
public class PaySwitchDetailsPaymentMethodsInnerTest {
    private final PaySwitchDetailsPaymentMethodsInner model = new PaySwitchDetailsPaymentMethodsInner();

    /**
     * Model tests for PaySwitchDetailsPaymentMethodsInner
     */
    @Test
    public void testPaySwitchDetailsPaymentMethodsInner() {
        // TODO: test PaySwitchDetailsPaymentMethodsInner
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'brand'
     */
    @Test
    public void brandTest() {
        // TODO: test brand
    }

    /**
     * Test the property 'bankIdentifier'
     */
    @Test
    public void bankIdentifierTest() {
        // TODO: test bankIdentifier
    }

    /**
     * Test the property 'endsWith'
     */
    @Test
    public void endsWithTest() {
        // TODO: test endsWith
    }

    /**
     * Test the property 'bankAccountType'
     */
    @Test
    public void bankAccountTypeTest() {
        // TODO: test bankAccountType
    }

}
