/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.PaySwitchDetailsPaymentMethodsInner;
import org.openapitools.client.model.PaySwitchDetailsProvider;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaySwitchDetails
 */
public class PaySwitchDetailsTest {
    private final PaySwitchDetails model = new PaySwitchDetails();

    /**
     * Model tests for PaySwitchDetails
     */
    @Test
    public void testPaySwitchDetails() {
        // TODO: test PaySwitchDetails
    }

    /**
     * Test the property 'customerId'
     */
    @Test
    public void customerIdTest() {
        // TODO: test customerId
    }

    /**
     * Test the property 'customerType'
     */
    @Test
    public void customerTypeTest() {
        // TODO: test customerType
    }

    /**
     * Test the property 'switchId'
     */
    @Test
    public void switchIdTest() {
        // TODO: test switchId
    }

    /**
     * Test the property 'switchStatus'
     */
    @Test
    public void switchStatusTest() {
        // TODO: test switchStatus
    }

    /**
     * Test the property 'failureReason'
     */
    @Test
    public void failureReasonTest() {
        // TODO: test failureReason
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    public void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'updatedDate'
     */
    @Test
    public void updatedDateTest() {
        // TODO: test updatedDate
    }

    /**
     * Test the property 'authenticated'
     */
    @Test
    public void authenticatedTest() {
        // TODO: test authenticated
    }

    /**
     * Test the property 'provider'
     */
    @Test
    public void providerTest() {
        // TODO: test provider
    }

    /**
     * Test the property 'paymentMethods'
     */
    @Test
    public void paymentMethodsTest() {
        // TODO: test paymentMethods
    }

}
