/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AccountOwnerHolders;
import org.openapitools.client.model.AccountSimpleDetails;
import org.openapitools.client.model.AvailableBalancePEB;
import org.openapitools.client.model.FieldError;
import org.openapitools.client.model.PaymentInstructionPEB;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PEBAccountDetails
 */
public class PEBAccountDetailsTest {
    private final PEBAccountDetails model = new PEBAccountDetails();

    /**
     * Model tests for PEBAccountDetails
     */
    @Test
    public void testPEBAccountDetails() {
        // TODO: test PEBAccountDetails
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'realAccountNumberLast4'
     */
    @Test
    public void realAccountNumberLast4Test() {
        // TODO: test realAccountNumberLast4
    }

    /**
     * Test the property 'institutionId'
     */
    @Test
    public void institutionIdTest() {
        // TODO: test institutionId
    }

    /**
     * Test the property 'institutionName'
     */
    @Test
    public void institutionNameTest() {
        // TODO: test institutionName
    }

    /**
     * Test the property 'institutionLoginId'
     */
    @Test
    public void institutionLoginIdTest() {
        // TODO: test institutionLoginId
    }

    /**
     * Test the property 'accountDetails'
     */
    @Test
    public void accountDetailsTest() {
        // TODO: test accountDetails
    }

    /**
     * Test the property 'balanceDetails'
     */
    @Test
    public void balanceDetailsTest() {
        // TODO: test balanceDetails
    }

    /**
     * Test the property 'accountIdentity'
     */
    @Test
    public void accountIdentityTest() {
        // TODO: test accountIdentity
    }

    /**
     * Test the property 'paymentInstruction'
     */
    @Test
    public void paymentInstructionTest() {
        // TODO: test paymentInstruction
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

}
