/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostInstitutionsInstitutionIdLoginForms201ResponseElementsInner
 */
public class PostInstitutionsInstitutionIdLoginForms201ResponseElementsInnerTest {
    private final PostInstitutionsInstitutionIdLoginForms201ResponseElementsInner model = new PostInstitutionsInstitutionIdLoginForms201ResponseElementsInner();

    /**
     * Model tests for PostInstitutionsInstitutionIdLoginForms201ResponseElementsInner
     */
    @Test
    public void testPostInstitutionsInstitutionIdLoginForms201ResponseElementsInner() {
        // TODO: test PostInstitutionsInstitutionIdLoginForms201ResponseElementsInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'sortOrder'
     */
    @Test
    public void sortOrderTest() {
        // TODO: test sortOrder
    }

}
