/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostReconnections203ResponseInnerMfaChallengesInner
 */
public class PostReconnections203ResponseInnerMfaChallengesInnerTest {
    private final PostReconnections203ResponseInnerMfaChallengesInner model = new PostReconnections203ResponseInnerMfaChallengesInner();

    /**
     * Model tests for PostReconnections203ResponseInnerMfaChallengesInner
     */
    @Test
    public void testPostReconnections203ResponseInnerMfaChallengesInner() {
        // TODO: test PostReconnections203ResponseInnerMfaChallengesInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'mfaType'
     */
    @Test
    public void mfaTypeTest() {
        // TODO: test mfaType
    }

    /**
     * Test the property 'prompt'
     */
    @Test
    public void promptTest() {
        // TODO: test prompt
    }

    /**
     * Test the property 'choiceIds'
     */
    @Test
    public void choiceIdsTest() {
        // TODO: test choiceIds
    }

}
