/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.Arrays;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostInstitutionsInstitutionIdOauthUrls201Response
 */
public class PostInstitutionsInstitutionIdOauthUrls201ResponseTest {
    private final PostInstitutionsInstitutionIdOauthUrls201Response model = new PostInstitutionsInstitutionIdOauthUrls201Response();

    /**
     * Model tests for PostInstitutionsInstitutionIdOauthUrls201Response
     */
    @Test
    public void testPostInstitutionsInstitutionIdOauthUrls201Response() {
        // TODO: test PostInstitutionsInstitutionIdOauthUrls201Response
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'eventStreamId'
     */
    @Test
    public void eventStreamIdTest() {
        // TODO: test eventStreamId
    }

}
