/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PrequalificationReportAssetSummary
 */
public class PrequalificationReportAssetSummaryTest {
    private final PrequalificationReportAssetSummary model = new PrequalificationReportAssetSummary();

    /**
     * Model tests for PrequalificationReportAssetSummary
     */
    @Test
    public void testPrequalificationReportAssetSummary() {
        // TODO: test PrequalificationReportAssetSummary
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'availableBalance'
     */
    @Test
    public void availableBalanceTest() {
        // TODO: test availableBalance
    }

    /**
     * Test the property 'currentBalance'
     */
    @Test
    public void currentBalanceTest() {
        // TODO: test currentBalance
    }

    /**
     * Test the property 'twoMonthAverage'
     */
    @Test
    public void twoMonthAverageTest() {
        // TODO: test twoMonthAverage
    }

    /**
     * Test the property 'sixMonthAverage'
     */
    @Test
    public void sixMonthAverageTest() {
        // TODO: test sixMonthAverage
    }

    /**
     * Test the property 'beginningBalance'
     */
    @Test
    public void beginningBalanceTest() {
        // TODO: test beginningBalance
    }

}
