/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AccountAnalytics;
import org.openapitools.client.model.AccountDetailsTxBased;
import org.openapitools.client.model.AnalyticsReportsAccount;
import org.openapitools.client.model.CashFlowCashFlowBalance;
import org.openapitools.client.model.CashFlowCashFlowCharacteristic;
import org.openapitools.client.model.CashFlowCashFlowCredit;
import org.openapitools.client.model.CashFlowCashFlowDebit;
import org.openapitools.client.model.CashFlowReportAccount;
import org.openapitools.client.model.PrequalificationReportAccount;
import org.openapitools.client.model.PrequalificationReportAssetSummary;
import org.openapitools.client.model.ReportAccountPosition;
import org.openapitools.client.model.ReportTransaction;
import org.openapitools.client.model.ReportTransactionNewTxBased;
import org.openapitools.client.model.TransactionsReportAccount;
import org.openapitools.client.model.VOAReportAccount;
import org.openapitools.client.model.VOAWithIncomeReportAccount;
import org.openapitools.client.model.VOETransactionsReportAccount;
import org.openapitools.client.model.VOIETXVerifyReportAccount;
import org.openapitools.client.model.VOIETXVerifyReportIncomeStream;
import org.openapitools.client.model.VOIReportAccount;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ReportInstitutionAccount
 */
public class ReportInstitutionAccountTest {
    private final ReportInstitutionAccount model = new ReportInstitutionAccount();

    /**
     * Model tests for ReportInstitutionAccount
     */
    @Test
    public void testReportInstitutionAccount() {
        // TODO: test ReportInstitutionAccount
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'ownerName'
     */
    @Test
    public void ownerNameTest() {
        // TODO: test ownerName
    }

    /**
     * Test the property 'ownerAddress'
     */
    @Test
    public void ownerAddressTest() {
        // TODO: test ownerAddress
    }

    /**
     * Test the property 'ownerAsOfDate'
     */
    @Test
    public void ownerAsOfDateTest() {
        // TODO: test ownerAsOfDate
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'number'
     */
    @Test
    public void numberTest() {
        // TODO: test number
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'aggregationStatusCode'
     */
    @Test
    public void aggregationStatusCodeTest() {
        // TODO: test aggregationStatusCode
    }

    /**
     * Test the property 'currentBalance'
     */
    @Test
    public void currentBalanceTest() {
        // TODO: test currentBalance
    }

    /**
     * Test the property 'availableBalance'
     */
    @Test
    public void availableBalanceTest() {
        // TODO: test availableBalance
    }

    /**
     * Test the property 'balanceDate'
     */
    @Test
    public void balanceDateTest() {
        // TODO: test balanceDate
    }

    /**
     * Test the property 'transactions'
     */
    @Test
    public void transactionsTest() {
        // TODO: test transactions
    }

    /**
     * Test the property 'details'
     */
    @Test
    public void detailsTest() {
        // TODO: test details
    }

    /**
     * Test the property 'analytics'
     */
    @Test
    public void analyticsTest() {
        // TODO: test analytics
    }

    /**
     * Test the property 'cashFlowBalance'
     */
    @Test
    public void cashFlowBalanceTest() {
        // TODO: test cashFlowBalance
    }

    /**
     * Test the property 'cashFlowCredit'
     */
    @Test
    public void cashFlowCreditTest() {
        // TODO: test cashFlowCredit
    }

    /**
     * Test the property 'cashFlowDebit'
     */
    @Test
    public void cashFlowDebitTest() {
        // TODO: test cashFlowDebit
    }

    /**
     * Test the property 'cashFlowCharacteristic'
     */
    @Test
    public void cashFlowCharacteristicTest() {
        // TODO: test cashFlowCharacteristic
    }

    /**
     * Test the property 'balance'
     */
    @Test
    public void balanceTest() {
        // TODO: test balance
    }

    /**
     * Test the property 'averageMonthlyBalance'
     */
    @Test
    public void averageMonthlyBalanceTest() {
        // TODO: test averageMonthlyBalance
    }

    /**
     * Test the property 'totNumberInsufficientFundsFeeDebitTxAccount'
     */
    @Test
    public void totNumberInsufficientFundsFeeDebitTxAccountTest() {
        // TODO: test totNumberInsufficientFundsFeeDebitTxAccount
    }

    /**
     * Test the property 'totNumberInsufficientFundsFeeDebitTxOver6MonthsAccount'
     */
    @Test
    public void totNumberInsufficientFundsFeeDebitTxOver6MonthsAccountTest() {
        // TODO: test totNumberInsufficientFundsFeeDebitTxOver6MonthsAccount
    }

    /**
     * Test the property 'totNumberDaysSinceMostRecentInsufficientFundsFeeDebitTxAccount'
     */
    @Test
    public void totNumberDaysSinceMostRecentInsufficientFundsFeeDebitTxAccountTest() {
        // TODO: test totNumberDaysSinceMostRecentInsufficientFundsFeeDebitTxAccount
    }

    /**
     * Test the property 'asset'
     */
    @Test
    public void assetTest() {
        // TODO: test asset
    }

    /**
     * Test the property 'oldestTransactionDate'
     */
    @Test
    public void oldestTransactionDateTest() {
        // TODO: test oldestTransactionDate
    }

    /**
     * Test the property 'transactionsCount'
     */
    @Test
    public void transactionsCountTest() {
        // TODO: test transactionsCount
    }

    /**
     * Test the property 'totNumberInsufficientFundsFeeDebitTxOver2MonthsAccount'
     */
    @Test
    public void totNumberInsufficientFundsFeeDebitTxOver2MonthsAccountTest() {
        // TODO: test totNumberInsufficientFundsFeeDebitTxOver2MonthsAccount
    }

    /**
     * Test the property 'position'
     */
    @Test
    public void positionTest() {
        // TODO: test position
    }

    /**
     * Test the property 'incomeStreams'
     */
    @Test
    public void incomeStreamsTest() {
        // TODO: test incomeStreams
    }

    /**
     * Test the property 'beginningBalance'
     */
    @Test
    public void beginningBalanceTest() {
        // TODO: test beginningBalance
    }

    /**
     * Test the property 'miscDeposits'
     */
    @Test
    public void miscDepositsTest() {
        // TODO: test miscDeposits
    }

}
