/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ReportAccountPosition
 */
public class ReportAccountPositionTest {
    private final ReportAccountPosition model = new ReportAccountPosition();

    /**
     * Model tests for ReportAccountPosition
     */
    @Test
    public void testReportAccountPosition() {
        // TODO: test ReportAccountPosition
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'symbol'
     */
    @Test
    public void symbolTest() {
        // TODO: test symbol
    }

    /**
     * Test the property 'securityName'
     */
    @Test
    public void securityNameTest() {
        // TODO: test securityName
    }

    /**
     * Test the property 'units'
     */
    @Test
    public void unitsTest() {
        // TODO: test units
    }

    /**
     * Test the property 'marketValue'
     */
    @Test
    public void marketValueTest() {
        // TODO: test marketValue
    }

    /**
     * Test the property 'currentPrice'
     */
    @Test
    public void currentPriceTest() {
        // TODO: test currentPrice
    }

    /**
     * Test the property 'securityType'
     */
    @Test
    public void securityTypeTest() {
        // TODO: test securityType
    }

}
