/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ReportIncomeEstimate
 */
public class ReportIncomeEstimateTest {
    private final ReportIncomeEstimate model = new ReportIncomeEstimate();

    /**
     * Model tests for ReportIncomeEstimate
     */
    @Test
    public void testReportIncomeEstimate() {
        // TODO: test ReportIncomeEstimate
    }

    /**
     * Test the property 'netAnnual'
     */
    @Test
    public void netAnnualTest() {
        // TODO: test netAnnual
    }

    /**
     * Test the property 'projectedNetAnnual'
     */
    @Test
    public void projectedNetAnnualTest() {
        // TODO: test projectedNetAnnual
    }

    /**
     * Test the property 'estimatedGrossAnnual'
     */
    @Test
    public void estimatedGrossAnnualTest() {
        // TODO: test estimatedGrossAnnual
    }

    /**
     * Test the property 'projectedGrossAnnual'
     */
    @Test
    public void projectedGrossAnnualTest() {
        // TODO: test projectedGrossAnnual
    }

}
