/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ReportTransactionBase2
 */
public class ReportTransactionBase2Test {
    private final ReportTransactionBase2 model = new ReportTransactionBase2();

    /**
     * Model tests for ReportTransactionBase2
     */
    @Test
    public void testReportTransactionBase2() {
        // TODO: test ReportTransactionBase2
    }

    /**
     * Test the property 'normalizedPayee'
     */
    @Test
    public void normalizedPayeeTest() {
        // TODO: test normalizedPayee
    }

    /**
     * Test the property 'institutionTransactionId'
     */
    @Test
    public void institutionTransactionIdTest() {
        // TODO: test institutionTransactionId
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'securityType'
     */
    @Test
    public void securityTypeTest() {
        // TODO: test securityType
    }

    /**
     * Test the property 'symbol'
     */
    @Test
    public void symbolTest() {
        // TODO: test symbol
    }

    /**
     * Test the property 'commission'
     */
    @Test
    public void commissionTest() {
        // TODO: test commission
    }

}
