/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ReportTransactionNewTxBased
 */
public class ReportTransactionNewTxBasedTest {
    private final ReportTransactionNewTxBased model = new ReportTransactionNewTxBased();

    /**
     * Model tests for ReportTransactionNewTxBased
     */
    @Test
    public void testReportTransactionNewTxBased() {
        // TODO: test ReportTransactionNewTxBased
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'postedDate'
     */
    @Test
    public void postedDateTest() {
        // TODO: test postedDate
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'memo'
     */
    @Test
    public void memoTest() {
        // TODO: test memo
    }

    /**
     * Test the property 'normalizedPayee'
     */
    @Test
    public void normalizedPayeeTest() {
        // TODO: test normalizedPayee
    }

    /**
     * Test the property 'institutionTransactionId'
     */
    @Test
    public void institutionTransactionIdTest() {
        // TODO: test institutionTransactionId
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'securityType'
     */
    @Test
    public void securityTypeTest() {
        // TODO: test securityType
    }

    /**
     * Test the property 'symbol'
     */
    @Test
    public void symbolTest() {
        // TODO: test symbol
    }

    /**
     * Test the property 'commission'
     */
    @Test
    public void commissionTest() {
        // TODO: test commission
    }

    /**
     * Test the property 'investmentTransactionType'
     */
    @Test
    public void investmentTransactionTypeTest() {
        // TODO: test investmentTransactionType
    }

}
