/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.NetMonthly;
import org.openapitools.client.model.ReportIncomeEstimate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ReportIncomeStreamSummary
 */
public class ReportIncomeStreamSummaryTest {
    private final ReportIncomeStreamSummary model = new ReportIncomeStreamSummary();

    /**
     * Model tests for ReportIncomeStreamSummary
     */
    @Test
    public void testReportIncomeStreamSummary() {
        // TODO: test ReportIncomeStreamSummary
    }

    /**
     * Test the property 'confidenceType'
     */
    @Test
    public void confidenceTypeTest() {
        // TODO: test confidenceType
    }

    /**
     * Test the property 'netMonthly'
     */
    @Test
    public void netMonthlyTest() {
        // TODO: test netMonthly
    }

    /**
     * Test the property 'incomeEstimate'
     */
    @Test
    public void incomeEstimateTest() {
        // TODO: test incomeEstimate
    }

}
