/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StatePeriod
 */
public class StatePeriodTest {
    private final StatePeriod model = new StatePeriod();

    /**
     * Model tests for StatePeriod
     */
    @Test
    public void testStatePeriod() {
        // TODO: test StatePeriod
    }

    /**
     * Test the property 'beginningValue'
     */
    @Test
    public void beginningValueTest() {
        // TODO: test beginningValue
    }

    /**
     * Test the property 'count'
     */
    @Test
    public void countTest() {
        // TODO: test count
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'endingValue'
     */
    @Test
    public void endingValueTest() {
        // TODO: test endingValue
    }

    /**
     * Test the property 'max'
     */
    @Test
    public void maxTest() {
        // TODO: test max
    }

    /**
     * Test the property 'mean'
     */
    @Test
    public void meanTest() {
        // TODO: test mean
    }

    /**
     * Test the property 'median'
     */
    @Test
    public void medianTest() {
        // TODO: test median
    }

    /**
     * Test the property 'min'
     */
    @Test
    public void minTest() {
        // TODO: test min
    }

    /**
     * Test the property 'standardDeviation'
     */
    @Test
    public void standardDeviationTest() {
        // TODO: test standardDeviation
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'sum'
     */
    @Test
    public void sumTest() {
        // TODO: test sum
    }

}
