/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ReportCustomField;
import org.openapitools.client.model.StatementData;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StatementReportConstraints
 */
public class StatementReportConstraintsTest {
    private final StatementReportConstraints model = new StatementReportConstraints();

    /**
     * Model tests for StatementReportConstraints
     */
    @Test
    public void testStatementReportConstraints() {
        // TODO: test StatementReportConstraints
    }

    /**
     * Test the property 'statementReportData'
     */
    @Test
    public void statementReportDataTest() {
        // TODO: test statementReportData
    }

    /**
     * Test the property 'reportCustomFields'
     */
    @Test
    public void reportCustomFieldsTest() {
        // TODO: test reportCustomFields
    }

}
