/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StreamModel
 */
public class StreamModelTest {
    private final StreamModel model = new StreamModel();

    /**
     * Model tests for StreamModel
     */
    @Test
    public void testStreamModel() {
        // TODO: test StreamModel
    }

    /**
     * Test the property 'cadence'
     */
    @Test
    public void cadenceTest() {
        // TODO: test cadence
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'payee'
     */
    @Test
    public void payeeTest() {
        // TODO: test payee
    }

    /**
     * Test the property 'payor'
     */
    @Test
    public void payorTest() {
        // TODO: test payor
    }

    /**
     * Test the property 'recency'
     */
    @Test
    public void recencyTest() {
        // TODO: test recency
    }

    /**
     * Test the property 'transactionIds'
     */
    @Test
    public void transactionIdsTest() {
        // TODO: test transactionIds
    }

}
