/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ThirdPartyAccessProof;
import org.openapitools.client.model.ThirdPartyAccessReceipt;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ThirdPartyAccessReceiptData
 */
public class ThirdPartyAccessReceiptDataTest {
    private final ThirdPartyAccessReceiptData model = new ThirdPartyAccessReceiptData();

    /**
     * Model tests for ThirdPartyAccessReceiptData
     */
    @Test
    public void testThirdPartyAccessReceiptData() {
        // TODO: test ThirdPartyAccessReceiptData
    }

    /**
     * Test the property 'receipt'
     */
    @Test
    public void receiptTest() {
        // TODO: test receipt
    }

    /**
     * Test the property 'proof'
     */
    @Test
    public void proofTest() {
        // TODO: test proof
    }

}
