/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ReportTransaction;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TransactionsReportAccount
 */
public class TransactionsReportAccountTest {
    private final TransactionsReportAccount model = new TransactionsReportAccount();

    /**
     * Model tests for TransactionsReportAccount
     */
    @Test
    public void testTransactionsReportAccount() {
        // TODO: test TransactionsReportAccount
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'number'
     */
    @Test
    public void numberTest() {
        // TODO: test number
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'aggregationStatusCode'
     */
    @Test
    public void aggregationStatusCodeTest() {
        // TODO: test aggregationStatusCode
    }

    /**
     * Test the property 'balance'
     */
    @Test
    public void balanceTest() {
        // TODO: test balance
    }

    /**
     * Test the property 'balanceDate'
     */
    @Test
    public void balanceDateTest() {
        // TODO: test balanceDate
    }

    /**
     * Test the property 'oldestTransactionDate'
     */
    @Test
    public void oldestTransactionDateTest() {
        // TODO: test oldestTransactionDate
    }

    /**
     * Test the property 'transactionsCount'
     */
    @Test
    public void transactionsCountTest() {
        // TODO: test transactionsCount
    }

    /**
     * Test the property 'transactions'
     */
    @Test
    public void transactionsTest() {
        // TODO: test transactions
    }

}
