/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.client.model.InputMerchantInformation;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TransactionPayload
 */
public class TransactionPayloadTest {
    private final TransactionPayload model = new TransactionPayload();

    /**
     * Model tests for TransactionPayload
     */
    @Test
    public void testTransactionPayload() {
        // TODO: test TransactionPayload
    }

    /**
     * Test the property 'externalCustomerId'
     */
    @Test
    public void externalCustomerIdTest() {
        // TODO: test externalCustomerId
    }

    /**
     * Test the property 'externalAccountId'
     */
    @Test
    public void externalAccountIdTest() {
        // TODO: test externalAccountId
    }

    /**
     * Test the property 'accountType'
     */
    @Test
    public void accountTypeTest() {
        // TODO: test accountType
    }

    /**
     * Test the property 'externalTransactionId'
     */
    @Test
    public void externalTransactionIdTest() {
        // TODO: test externalTransactionId
    }

    /**
     * Test the property 'postedTimestamp'
     */
    @Test
    public void postedTimestampTest() {
        // TODO: test postedTimestamp
    }

    /**
     * Test the property 'transactionTimestamp'
     */
    @Test
    public void transactionTimestampTest() {
        // TODO: test transactionTimestamp
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'memo'
     */
    @Test
    public void memoTest() {
        // TODO: test memo
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'transactionFee'
     */
    @Test
    public void transactionFeeTest() {
        // TODO: test transactionFee
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'directionIndicator'
     */
    @Test
    public void directionIndicatorTest() {
        // TODO: test directionIndicator
    }

    /**
     * Test the property 'additionalDetails'
     */
    @Test
    public void additionalDetailsTest() {
        // TODO: test additionalDetails
    }

    /**
     * Test the property 'cardAcceptorId'
     */
    @Test
    public void cardAcceptorIdTest() {
        // TODO: test cardAcceptorId
    }

    /**
     * Test the property 'inputIsRecurringTransaction'
     */
    @Test
    public void inputIsRecurringTransactionTest() {
        // TODO: test inputIsRecurringTransaction
    }

    /**
     * Test the property 'inputMerchantInformation'
     */
    @Test
    public void inputMerchantInformationTest() {
        // TODO: test inputMerchantInformation
    }

}
