/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.CadenceDetails;
import org.openapitools.client.model.ReportTransaction;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VOETransactionsReportIncomeStream
 */
public class VOETransactionsReportIncomeStreamTest {
    private final VOETransactionsReportIncomeStream model = new VOETransactionsReportIncomeStream();

    /**
     * Model tests for VOETransactionsReportIncomeStream
     */
    @Test
    public void testVOETransactionsReportIncomeStream() {
        // TODO: test VOETransactionsReportIncomeStream
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'estimateInclusion'
     */
    @Test
    public void estimateInclusionTest() {
        // TODO: test estimateInclusion
    }

    /**
     * Test the property 'confidence'
     */
    @Test
    public void confidenceTest() {
        // TODO: test confidence
    }

    /**
     * Test the property 'cadence'
     */
    @Test
    public void cadenceTest() {
        // TODO: test cadence
    }

    /**
     * Test the property 'daysSinceLastTransaction'
     */
    @Test
    public void daysSinceLastTransactionTest() {
        // TODO: test daysSinceLastTransaction
    }

    /**
     * Test the property 'nextExpectedTransactionDate'
     */
    @Test
    public void nextExpectedTransactionDateTest() {
        // TODO: test nextExpectedTransactionDate
    }

    /**
     * Test the property 'incomeStreamMonths'
     */
    @Test
    public void incomeStreamMonthsTest() {
        // TODO: test incomeStreamMonths
    }

    /**
     * Test the property 'transactions'
     */
    @Test
    public void transactionsTest() {
        // TODO: test transactions
    }

}
