/*
 * Open Finance
 * OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.31.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VOIEWithStatementData
 */
public class VOIEWithStatementDataTest {
    private final VOIEWithStatementData model = new VOIEWithStatementData();

    /**
     * Model tests for VOIEWithStatementData
     */
    @Test
    public void testVOIEWithStatementData() {
        // TODO: test VOIEWithStatementData
    }

    /**
     * Test the property 'assetIds'
     */
    @Test
    public void assetIdsTest() {
        // TODO: test assetIds
    }

    /**
     * Test the property 'extractEarnings'
     */
    @Test
    public void extractEarningsTest() {
        // TODO: test extractEarnings
    }

    /**
     * Test the property 'extractDeductions'
     */
    @Test
    public void extractDeductionsTest() {
        // TODO: test extractDeductions
    }

    /**
     * Test the property 'extractDirectDeposit'
     */
    @Test
    public void extractDirectDepositTest() {
        // TODO: test extractDirectDeposit
    }

}
